#!/usr/bin/env python3
"""Build the original, browser-ready Gary polar-bear assets.

This is an authored Blender pipeline, not a runtime assembly of spheres.  The
script fuses a deliberately blocked anatomical sculpt, voxel-remeshes it into
one watertight skin, refines the silhouette, UV unwraps the result, binds it to
an explicit quadruped skeleton, authors four actions, and exports two GLBs.

Run with Blender (3.4 or newer):

  /Applications/Blender.app/Contents/MacOS/Blender \
    --background --factory-startup \
    --python tools/animal-pipeline/build_gary.py -- \
    --output public/game/animals/authored \
    --preview /tmp/sloth-animal-previews

All source geometry, textures, weights and animation curves are generated by
this repository script. Wildlife photographs may be consulted for proportion
reference, but no third-party meshes or texture pixels enter the output.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import struct
import sys
import tempfile
from pathlib import Path
from typing import Dict, Iterable, List, Sequence, Tuple

import bpy
import bmesh
from mathutils import Matrix, Vector

try:
    import numpy as np
except ImportError as exc:  # Blender's official builds include NumPy.
    raise RuntimeError("The Gary pipeline requires Blender's bundled NumPy") from exc


ASSET_ID = "gary-polar-bear"
CLIP_NAMES = ("BearIdle", "BearWalk", "BearForage", "BearTurn")
TEXTURE_SIZE = 2048


def parse_args() -> argparse.Namespace:
    argv = sys.argv[sys.argv.index("--") + 1 :] if "--" in sys.argv else []
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--source", type=Path, default=Path(__file__).resolve().parent / "source")
    parser.add_argument("--preview", type=Path)
    parser.add_argument("--keep-blend", action="store_true")
    parser.add_argument("--texture-size", type=int, default=TEXTURE_SIZE)
    parser.add_argument("--voxel-size", type=float, default=0.023)
    return parser.parse_args(argv)


def ensure_object_mode() -> None:
    if bpy.context.object and bpy.context.object.mode != "OBJECT":
        bpy.ops.object.mode_set(mode="OBJECT")


def select_only(objects: Iterable[bpy.types.Object]) -> None:
    ensure_object_mode()
    bpy.ops.object.select_all(action="DESELECT")
    active = None
    for obj in objects:
        obj.hide_set(False)
        obj.hide_viewport = False
        obj.hide_render = False
        obj.select_set(True)
        active = obj
    if active is not None:
        bpy.context.view_layer.objects.active = active


def purge_scene() -> None:
    ensure_object_mode()
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)
    for datablocks in (
        bpy.data.meshes,
        bpy.data.curves,
        bpy.data.armatures,
        bpy.data.materials,
        bpy.data.images,
        bpy.data.actions,
    ):
        for block in list(datablocks):
            if block.users == 0:
                datablocks.remove(block)


def apply_modifiers(obj: bpy.types.Object) -> None:
    select_only([obj])
    bpy.context.view_layer.objects.active = obj
    for modifier in list(obj.modifiers):
        bpy.ops.object.modifier_apply(modifier=modifier.name)


def add_volume(
    name: str,
    location: Sequence[float],
    scale: Sequence[float],
    rotation: Sequence[float] = (0.0, 0.0, 0.0),
    subdivisions: int = 2,
) -> bpy.types.Object:
    """Add a sculpt volume; every volume is fused before it can ship."""
    bpy.ops.mesh.primitive_ico_sphere_add(subdivisions=subdivisions, radius=1.0, location=location)
    obj = bpy.context.object
    obj.name = f"SculptVolume.{name}"
    obj.scale = scale
    obj.rotation_euler = rotation
    select_only([obj])
    bpy.ops.object.transform_apply(location=False, rotation=True, scale=True)
    return obj


def make_body(voxel_size: float) -> bpy.types.Object:
    """Create a single watertight polar-bear skin from an anatomical blockout.

    The volumes overlap only as a sculpting aid.  Voxel remeshing replaces all
    of their surfaces with one new manifold surface, so the exported body has
    no intersecting shells, floating paws, or sphere seams.
    """
    volumes: List[bpy.types.Object] = []
    add = lambda name, loc, scale, rot=(0.0, 0.0, 0.0), sub=2: volumes.append(
        add_volume(name, loc, scale, rot, sub)
    )

    # Long, powerful but not obese ursine trunk. +Y is the nose direction in
    # Blender and becomes -Z (THREE forward) in the exported y-up glTF.
    add("RibCage", (0.0, 0.02, 1.40), (0.69, 1.47, 0.59), (math.radians(-3), 0, 0), 3)
    add("ShoulderGirdle", (0.0, 0.58, 1.50), (0.70, 0.84, 0.62), (math.radians(-6), 0, 0), 3)
    add("Pelvis", (0.0, -0.86, 1.35), (0.63, 0.82, 0.53), (math.radians(4), 0, 0), 3)
    add("AbdomenTaper", (0.0, -0.32, 1.31), (0.63, 0.91, 0.49), (0, 0, 0), 2)
    add("Withers", (0.0, 0.40, 1.72), (0.52, 0.72, 0.38), (math.radians(-8), 0, 0), 2)

    # Neck and head form a low, tapered polar-bear profile, not a round teddy
    # head. The muzzle is substantially longer than a brown bear's.
    add("LowerNeck", (0.0, 1.15, 1.54), (0.54, 0.84, 0.51), (math.radians(-14), 0, 0), 3)
    add("UpperNeck", (0.0, 1.52, 1.61), (0.46, 0.76, 0.42), (math.radians(-12), 0, 0), 3)
    add("Cranium", (0.0, 1.78, 1.69), (0.43, 0.50, 0.38), (math.radians(-7), 0, 0), 3)
    add("CheekL", (0.22, 1.99, 1.61), (0.24, 0.36, 0.25), (0, math.radians(-8), 0), 2)
    add("CheekR", (-0.22, 1.99, 1.61), (0.24, 0.36, 0.25), (0, math.radians(8), 0), 2)
    add("MuzzleBridge", (0.0, 2.20, 1.60), (0.27, 0.48, 0.21), (math.radians(-8), 0, 0), 3)
    add("MuzzlePad", (0.0, 2.53, 1.54), (0.29, 0.32, 0.21), (math.radians(-10), 0, 0), 2)
    add("Chin", (0.0, 2.34, 1.41), (0.275, 0.43, 0.16), (math.radians(-7), 0, 0), 2)
    # Small, rounded ears embedded deep in the coat.
    add("EarL", (0.40, 1.53, 1.83), (0.065, 0.050, 0.060), (math.radians(8), 0, math.radians(-20)), 2)
    add("EarR", (-0.40, 1.53, 1.83), (0.065, 0.050, 0.060), (math.radians(8), 0, math.radians(20)), 2)

    # Forelegs drop almost straight beneath the shoulders.  Multiple tapered
    # volumes describe scapula, upper limb, wrist and broad five-toed paw.
    for side_name, x in (("L", 0.53), ("R", -0.53)):
        add(f"Scapula{side_name}", (x, 0.67, 1.36), (0.28, 0.36, 0.44), (0, math.radians(3 if x > 0 else -3), 0), 2)
        add(f"ForeUpper{side_name}", (x, 0.74, 0.95), (0.23, 0.25, 0.46), (math.radians(-2), 0, 0), 2)
        add(f"ForeWrist{side_name}", (x, 0.78, 0.49), (0.155, 0.18, 0.34), (math.radians(-1), 0, 0), 2)
        add(f"ForeCarpal{side_name}", (x, 0.84, 0.25), (0.145, 0.17, 0.15), (math.radians(-8), 0, 0), 2)
        paw_rotation = math.radians(5 if x > 0 else -5)
        add(f"ForeKnuckle{side_name}", (x - math.copysign(.02, x), 1.04, 0.16), (0.205, 0.23, 0.13), (math.radians(-7), 0, paw_rotation), 2)
        add(f"ForePaw{side_name}", (x - math.copysign(.02, x), 1.03, 0.09), (0.205, 0.34, 0.09), (math.radians(-4), 0, paw_rotation), 2)
        for digit, offset in enumerate((-.095, -.032, .032, .095)):
            add(
                f"ForeToeWeb{side_name}{digit}",
                (x - math.copysign(.02, x) + offset, 1.27, .075),
                (.059, .13, .065),
                (math.radians(-6), 0, paw_rotation),
                2,
            )

    # Hind legs retain the characteristic powerful thigh and plantigrade hock.
    for side_name, x in (("L", 0.51), ("R", -0.51)):
        add(f"Thigh{side_name}", (x, -0.78, 1.14), (0.34, 0.45, 0.52), (math.radians(5), 0, 0), 2)
        add(f"HindKnee{side_name}", (x, -0.84, 0.78), (0.25, 0.30, 0.34), (math.radians(4), 0, 0), 2)
        add(f"HindHock{side_name}", (x, -0.67, 0.44), (0.17, 0.29, 0.29), (math.radians(-14), 0, 0), 2)
        add(f"HindAnkle{side_name}", (x, -0.48, 0.24), (0.17, 0.22, 0.145), (math.radians(-16), 0, 0), 2)
        paw_rotation = math.radians(4 if x > 0 else -4)
        add(f"HindKnuckle{side_name}", (x - math.copysign(.015, x), -0.18, 0.16), (0.21, 0.25, 0.13), (math.radians(-8), 0, paw_rotation), 2)
        add(f"HindPaw{side_name}", (x - math.copysign(.015, x), -0.22, 0.09), (0.215, 0.38, 0.09), (math.radians(-5), 0, paw_rotation), 2)
        for digit, offset in enumerate((-.10, -.034, .034, .10)):
            add(
                f"HindToeWeb{side_name}{digit}",
                (x - math.copysign(.015, x) + offset, .07, .075),
                (.063, .13, .065),
                (math.radians(-7), 0, paw_rotation),
                2,
            )

    add("TailBase", (0.0, -1.41, 1.30), (0.22, 0.28, 0.24), (math.radians(-18), 0, 0), 2)

    # One manifold surface replaces every blockout volume.
    select_only(volumes)
    bpy.context.view_layer.objects.active = volumes[0]
    bpy.ops.object.join()
    body = bpy.context.object
    body.name = "Body"
    body.data.name = "GaryContinuousAnatomicalSkin"
    body.data.remesh_voxel_size = voxel_size
    body.data.remesh_voxel_adaptivity = 0.0
    select_only([body])
    bpy.ops.object.voxel_remesh()

    # Relax voxel stair-stepping while retaining shoulder, hock and muzzle
    # planes. A restrained multi-octave displacement gives the silhouette the
    # irregularity of dense guard fur without ballooning the anatomy.
    smooth = body.modifiers.new("Anatomical surface relaxation", "SMOOTH")
    smooth.factor = 0.48
    smooth.iterations = 12
    apply_modifiers(body)

    refine_anatomical_planes(body)

    fur_texture = bpy.data.textures.new("GaryGuardHairMicroSculpt", type="CLOUDS")
    fur_texture.noise_scale = 0.035
    fur_texture.noise_depth = 2
    displacement = body.modifiers.new("Guard hair micro silhouette", "DISPLACE")
    displacement.texture = fur_texture
    displacement.strength = 0.0028
    displacement.texture_coords = "GLOBAL"
    displacement.mid_level = 0.56
    apply_modifiers(body)

    # Give all four paws a shared planted contact plane. Preserve the rounded
    # toe walls above it, but remove the rocking-chair underside that makes a
    # heavy quadruped look weightless on level habitat ground.
    inverse = body.matrix_world.inverted()
    for vertex in body.data.vertices:
        world = body.matrix_world @ vertex.co
        if world.z < .052:
            world.z = .026
            vertex.co = inverse @ world
        elif world.z < .095:
            blend = (world.z - .052) / (.095 - .052)
            world.z = .026 * (1.0 - blend) + world.z * blend
            vertex.co = inverse @ world
    body.data.update()

    for polygon in body.data.polygons:
        polygon.use_smooth = True
    body["continuous_anatomical_mesh"] = True
    body["source_geometry"] = "original-repository-authored"
    return body


def refine_anatomical_planes(body: bpy.types.Object) -> None:
    """Hand-shape the fused skin into adult polar-bear planes.

    The voxel union guarantees one continuous surface. This deterministic
    vertex pass supplies the concave orbit, brow/cheek breaks, long nasal
    taper, jaw plane and limb-joint pinches that overlapping ellipsoids cannot
    describe on their own. It is symmetric, non-destructive to topology, and
    uses no external model or sampled geometry.
    """
    inverse = body.matrix_world.inverted()

    def gaussian(value: float, center: float, radius: float) -> float:
        return math.exp(-((value - center) / radius) ** 2)

    for vertex in body.data.vertices:
        point = body.matrix_world @ vertex.co
        x, y, z = point
        side = abs(x)
        sign = -1.0 if x < 0 else 1.0

        # A low crown and held brow replace the domed teddy-bear forehead.
        crown = gaussian(y, 1.78, .43) * max(0.0, min(1.0, (z - 1.74) / .26))
        point.z -= crown * .045

        if side > .12:
            orbit = gaussian(y, 2.07, .19) * gaussian(z, 1.68, .14)
            brow = gaussian(y, 1.99, .20) * gaussian(z, 1.80, .075)
            cheek = gaussian(y, 2.12, .23) * gaussian(z, 1.50, .12)
            jaw = gaussian(y, 2.39, .34) * gaussian(z, 1.34, .10)
            facial_delta = -orbit * .042 + brow * .018 + cheek * .030 + jaw * .012
            point.x = sign * max(.015, side + facial_delta)

        # Recess the eye opening in the forward-facing skull surface, then
        # hold a narrow upper lid/brow and a subtler lower lid around it. The
        # separate dark eye insert sits almost flush behind these skin planes.
        if y > 2.02:
            eye_center_x = math.copysign(.30, x)
            eye_width = gaussian(x, eye_center_x, .115)
            face_front = max(0.0, min(1.0, (y - 2.02) / .23))
            socket = gaussian(z, 1.675, .085)
            upper_lid = gaussian(z, 1.705, .035)
            lower_lid = gaussian(z, 1.645, .030)
            brow_plane = gaussian(z, 1.755, .040)
            point.y += eye_width * face_front * (
                -socket * .024
                + upper_lid * .018
                + lower_lid * .010
                + brow_plane * .014
            )

        # Narrow the bony bridge before the soft muzzle expands distally.
        bridge = gaussian(y, 2.28, .30) * gaussian(z, 1.61, .27)
        distal_release = max(0.0, min(1.0, (y - 2.48) / .28))
        if y > 2.02:
            taper = 1.0 - bridge * .13 * (1.0 - distal_release)
            point.x *= taper

        # Separate the lower jaw/chin plane from the upper muzzle bulb.
        chin = gaussian(y, 2.38, .36) * max(0.0, min(1.0, (1.49 - z) / .20))
        point.z -= chin * .025

        # Preserve identifiable elbow/carpal and knee/hock changes rather than
        # leaving constant-width columns. Each field pinches only the local
        # transverse section and leaves the continuous joins intact.
        for limb_x in (-.53, .53):
            if abs(x - limb_x) < .34:
                fore_y = gaussian(y, .78, .30)
                fore_joint = fore_y * (
                    gaussian(z, .80, .13) * .055
                    + gaussian(z, .38, .11) * .075
                )
                hind_y = gaussian(y, -.72, .36)
                hind_joint = hind_y * (
                    gaussian(z, .76, .14) * .045
                    + gaussian(z, .43, .11) * .070
                )
                pinch = max(fore_joint, hind_joint)
                if pinch > 0:
                    local_x = point.x - limb_x
                    point.x = limb_x + local_x * (1.0 - pinch)

        # Shallow dorsal channels separate the four visible toe webs without
        # cutting through the paw or creating detachable digits. The sole and
        # interdigital base remain one load-bearing manifold surface.
        paw_center = math.copysign(.51, point.x) if abs(point.x) > .24 else 0.0
        local_paw_x = point.x - paw_center
        if paw_center and abs(local_paw_x) < .19 and point.z > .10:
            toe_field = max(gaussian(y, 1.27, .15), gaussian(y, .07, .15))
            groove = max(gaussian(local_paw_x, offset, .016) for offset in (-.07, 0.0, .07))
            dorsal = max(0.0, min(1.0, (point.z - .10) / .075))
            point.z -= toe_field * groove * dorsal * .014

        vertex.co = inverse @ point
    body.data.update()


def smart_uv(obj: bpy.types.Object) -> None:
    select_only([obj])
    bpy.context.view_layer.objects.active = obj
    bpy.ops.object.mode_set(mode="EDIT")
    bpy.ops.mesh.select_all(action="SELECT")
    # Keep broad torso/head/limb planes in larger coherent islands. The old
    # 52-degree split fragmented the deforming flank into many tiny islands,
    # making tangent-normal boundaries visible during the walk cycle.
    bpy.ops.uv.smart_project(angle_limit=math.radians(82), island_margin=0.008)
    bpy.ops.object.mode_set(mode="OBJECT")


def write_texture_set(output: Path, size: int) -> Dict[str, Path]:
    """Create original fur PBR maps; no source pixels or model assets used."""
    output.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(93479021)
    u = np.linspace(0.0, 1.0, size, endpoint=False, dtype=np.float32)
    v = np.linspace(0.0, 1.0, size, endpoint=False, dtype=np.float32)
    xx, yy = np.meshgrid(u, v)

    # Dense short-fur breakup: filtered micro-noise supplies individual guard
    # hair clusters, while many low-frequency directions create non-repeating
    # undercoat variation. A previous four-sine version produced long grooves;
    # this deliberately has no dominant continuous stripe direction.
    fine = rng.normal(0.0, 1.0, (size, size)).astype(np.float32)
    for _ in range(3):
        fine = (
            fine * 2.0
            + np.roll(fine, 1, 0) + np.roll(fine, -1, 0)
            + np.roll(fine, 1, 1) + np.roll(fine, -1, 1)
        ) / 6.0
    fine /= max(float(fine.std()), 1e-6)
    micro = rng.normal(0.0, 1.0, (size, size)).astype(np.float32)
    micro = (micro * 2.0 + np.roll(micro, 1, 0) + np.roll(micro, -1, 0) + np.roll(micro, 1, 1) + np.roll(micro, -1, 1)) / 6.0
    micro /= max(float(micro.std()), 1e-6)
    broad = np.zeros((size, size), dtype=np.float32)
    for _ in range(18):
        angle = float(rng.uniform(0, math.tau))
        frequency = float(rng.uniform(1.8, 11.0))
        phase = float(rng.uniform(0, math.tau))
        broad += np.sin((xx * math.cos(angle) + yy * math.sin(angle)) * math.tau * frequency + phase)
    broad /= max(float(broad.std()), 1e-6)
    height = np.clip(fine * .48 + micro * .20 + broad * .10, -1.0, 1.0)

    base = np.zeros((size, size, 4), dtype=np.float32)
    warmth = np.clip(.5 + broad * .10, 0, 1)
    luminosity = np.clip(.78 + height * .055 + broad * .025, .62, .92)
    base[..., 0] = np.clip(luminosity * (1.02 + warmth * .018), 0, 1)
    base[..., 1] = np.clip(luminosity * (1.00 + warmth * .006), 0, 1)
    base[..., 2] = np.clip(luminosity * (.91 - warmth * .018), 0, 1)
    base[..., 3] = 1.0

    # Tangent-space normals from the same directional height field.
    grad_y, grad_x = np.gradient(height)
    strength = 1.35
    nx = -grad_x * strength
    ny = -grad_y * strength
    nz = np.ones_like(nx)
    norm = np.sqrt(nx * nx + ny * ny + nz * nz)
    normal = np.stack((nx / norm * .5 + .5, ny / norm * .5 + .5, nz / norm * .5 + .5, np.ones_like(nx)), axis=-1)

    roughness_value = np.clip(.80 + height * .055 + broad * .04, .68, .94)
    roughness = np.stack((roughness_value, roughness_value, roughness_value, np.ones_like(height)), axis=-1)

    paths = {
        "albedo": output / f"{ASSET_ID}-albedo.png",
        "normal": output / f"{ASSET_ID}-normal.png",
        "roughness": output / f"{ASSET_ID}-roughness.png",
    }
    for kind, pixels in (("albedo", base), ("normal", normal), ("roughness", roughness)):
        image = bpy.data.images.new(f"GaryFur{kind.title()}", width=size, height=size, alpha=True, float_buffer=False)
        # Blender image pixels are bottom-up; symmetry makes the flip harmless,
        # but preserve conventional texture orientation anyway.
        image.pixels.foreach_set(np.flipud(pixels).reshape(-1))
        image.filepath_raw = str(paths[kind])
        image.file_format = "PNG"
        image.save()
        bpy.data.images.remove(image)
    return paths


def make_runtime_texture_set(source_paths: Dict[str, Path]) -> Dict[str, Path]:
    """Transcode source PNGs to high-quality embedded web delivery images."""
    runtime_dir = Path(tempfile.gettempdir()) / "sloth-gary-runtime-textures"
    runtime_dir.mkdir(parents=True, exist_ok=True)
    runtime_paths: Dict[str, Path] = {}
    for kind, source in source_paths.items():
        image = bpy.data.images.load(str(source), check_existing=False)
        # Force lazy disk pixels resident before changing the destination path.
        _ = image.pixels[0]
        # glTF repacks metallic/roughness channels into a PNG. Downsample only
        # this low-frequency delivery map to avoid a multi-megabyte packed PNG;
        # the editable 2K roughness source remains lossless above.
        if kind == "roughness":
            image.scale(1024, 1024)
        destination = runtime_dir / f"{ASSET_ID}-{kind}.{'png' if kind == 'roughness' else 'jpg'}"
        image.filepath_raw = str(destination)
        image.file_format = "PNG" if kind == "roughness" else "JPEG"
        image.save()
        runtime_paths[kind] = destination
        bpy.data.images.remove(image)
    return runtime_paths


def relink_fur_material(material: bpy.types.Material, texture_paths: Dict[str, Path]) -> None:
    names = {
        "albedo": "Gary original fur albedo",
        "normal": "Gary original guard-hair normal",
        "roughness": "Gary original fur roughness",
    }
    for kind, node_name in names.items():
        node = material.node_tree.nodes[node_name]
        old = node.image
        node.image = bpy.data.images.load(str(texture_paths[kind]), check_existing=True)
        if kind != "albedo":
            node.image.colorspace_settings.name = "Non-Color"
        if old and old.users == 0:
            bpy.data.images.remove(old)


def principled_node(material: bpy.types.Material):
    return material.node_tree.nodes.get("Principled BSDF")


def make_fur_material(texture_paths: Dict[str, Path]) -> bpy.types.Material:
    material = bpy.data.materials.new("GaryPolarBearFur")
    material.use_nodes = True
    nodes = material.node_tree.nodes
    links = material.node_tree.links
    principled = principled_node(material)
    principled.inputs["Base Color"].default_value = (0.82, 0.81, 0.73, 1.0)
    principled.inputs["Roughness"].default_value = 0.84
    if "Sheen" in principled.inputs:
        principled.inputs["Sheen"].default_value = 0.16

    albedo_node = nodes.new("ShaderNodeTexImage")
    albedo_node.name = "Gary original fur albedo"
    albedo_node.image = bpy.data.images.load(str(texture_paths["albedo"]))
    albedo_node.image.colorspace_settings.name = "sRGB"
    links.new(albedo_node.outputs["Color"], principled.inputs["Base Color"])

    rough_node = nodes.new("ShaderNodeTexImage")
    rough_node.name = "Gary original fur roughness"
    rough_node.image = bpy.data.images.load(str(texture_paths["roughness"]))
    rough_node.image.colorspace_settings.name = "Non-Color"
    links.new(rough_node.outputs["Color"], principled.inputs["Roughness"])

    normal_node = nodes.new("ShaderNodeTexImage")
    normal_node.name = "Gary original guard-hair normal"
    normal_node.image = bpy.data.images.load(str(texture_paths["normal"]))
    normal_node.image.colorspace_settings.name = "Non-Color"
    normal_map = nodes.new("ShaderNodeNormalMap")
    # Geometry already carries a guard-hair micro-sculpt. The map supplies a
    # restrained secondary response without overpowering anatomy or exposing
    # UV tangent transitions under animation.
    normal_map.inputs["Strength"].default_value = 0.12
    links.new(normal_node.outputs["Color"], normal_map.inputs["Color"])
    links.new(normal_map.outputs["Normal"], principled.inputs["Normal"])
    return material


def simple_material(name: str, color: Sequence[float], roughness: float, metallic: float = 0.0) -> bpy.types.Material:
    material = bpy.data.materials.new(name)
    material.use_nodes = True
    material.diffuse_color = tuple(color)
    node = principled_node(material)
    node.inputs["Base Color"].default_value = tuple(color)
    node.inputs["Roughness"].default_value = roughness
    node.inputs["Metallic"].default_value = metallic
    if "Specular" in node.inputs:
        node.inputs["Specular"].default_value = 0.42
    return material


def add_ellipsoid(name: str, location: Sequence[float], scale: Sequence[float], material: bpy.types.Material, segments: int = 24) -> bpy.types.Object:
    bpy.ops.mesh.primitive_uv_sphere_add(segments=segments, ring_count=max(12, segments // 2), radius=1.0, location=location)
    obj = bpy.context.object
    obj.name = name
    obj.scale = scale
    select_only([obj])
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    obj.data.materials.append(material)
    for polygon in obj.data.polygons:
        polygon.use_smooth = True
    return obj


def curve_mesh(name: str, points: Sequence[Sequence[float]], radius: float, material: bpy.types.Material, resolution: int = 3) -> bpy.types.Object:
    curve = bpy.data.curves.new(name, type="CURVE")
    curve.dimensions = "3D"
    curve.resolution_u = resolution
    curve.bevel_depth = radius
    curve.bevel_resolution = 3
    spline = curve.splines.new("BEZIER")
    spline.bezier_points.add(len(points) - 1)
    for point, coordinate in zip(spline.bezier_points, points):
        point.co = coordinate
        point.handle_left_type = "AUTO"
        point.handle_right_type = "AUTO"
    obj = bpy.data.objects.new(name, curve)
    bpy.context.collection.objects.link(obj)
    obj.data.materials.append(material)
    select_only([obj])
    bpy.context.view_layer.objects.active = obj
    bpy.ops.object.convert(target="MESH")
    return bpy.context.object


def make_details(materials: Dict[str, bpy.types.Material]) -> Dict[str, bpy.types.Object]:
    details: Dict[str, bpy.types.Object] = {}
    eyes = []
    for side, x in (("L", .29), ("R", -.29)):
        eye = add_ellipsoid(f"Eye.{side}", (x, 2.255, 1.67), (.035, .010, .017), materials["eyes"], 32)
        # Rotate the flattened eye surface toward the diagonal side of skull.
        eye.rotation_euler.z = math.radians(-10 if side == "L" else 10)
        eyes.append(eye)
    select_only(eyes)
    bpy.context.view_layer.objects.active = eyes[0]
    bpy.ops.object.join()
    details["eyes"] = bpy.context.object
    details["eyes"].name = "Eyes"

    nose = add_ellipsoid("Nose", (0.0, 2.815, 1.50), (.145, .085, .085), materials["nose"], 40)
    # A polar bear's nasal pad is a broad, low pear/triangle, not a bead at
    # the end of the muzzle. Hold the upper plane, taper into the philtrum and
    # leave the shallow rear third embedded in the fused muzzle skin.
    for vertex in nose.data.vertices:
        normalized_z = max(-1.0, min(1.0, vertex.co.z / .085))
        width = max(.68, 1.05 + .28 * normalized_z)
        vertex.co.x *= width
        if vertex.co.y < 0.0:
            vertex.co.y *= .55
        else:
            vertex.co.y *= .45
    nose.data.update()
    details["nose"] = nose

    inner_ears = []
    for side, x in (("L", .385), ("R", -.385)):
        # A restrained inset catches a hint of warm ear skin without becoming
        # a rigid card that silhouettes outside the dense outer-ear fur when
        # the head turns or lowers.
        inner_ears.append(add_ellipsoid(f"InnerEar.{side}", (x, 1.532, 1.825), (.018, .008, .014), materials["inner_ear"], 24))
    select_only(inner_ears)
    bpy.context.view_layer.objects.active = inner_ears[0]
    bpy.ops.object.join()
    details["inner_ears"] = bpy.context.object
    details["inner_ears"].name = "InnerEars"

    mouth = curve_mesh(
        "MouthLine",
        ((-.14, 2.73, 1.405), (0.0, 2.79, 1.400), (.14, 2.73, 1.405)),
        .005,
        materials["mouth"],
    )
    philtrum = curve_mesh("Philtrum", ((0.0, 2.82, 1.46), (0.0, 2.785, 1.400)), .005, materials["mouth"])
    select_only([mouth, philtrum])
    bpy.context.view_layer.objects.active = mouth
    bpy.ops.object.join()
    details["mouth"] = bpy.context.object
    details["mouth"].name = "Mouth"

    claws = []
    # Four restrained keratin claws per paw, embedded at their bases.
    for paw, x, y in (
        ("ForeL", .51, 1.27), ("ForeR", -.51, 1.27),
        ("HindL", .495, .07), ("HindR", -.495, .07),
    ):
        for digit in range(4):
            dx = (digit - 1.5) * .067
            bpy.ops.mesh.primitive_cone_add(
                vertices=12,
                radius1=.015,
                radius2=.005,
                depth=.055,
                location=(x + dx, y + .025, .095),
                rotation=(math.radians(-72), 0, 0),
            )
            claw = bpy.context.object
            claw.name = f"Claw.{paw}.{digit}"
            claw.data.materials.append(materials["claw"])
            claws.append(claw)
    select_only(claws)
    bpy.context.view_layer.objects.active = claws[0]
    bpy.ops.object.join()
    details["claws"] = bpy.context.object
    details["claws"].name = "Claws"
    for obj in details.values():
        obj.data.name = obj.name
        for polygon in obj.data.polygons:
            polygon.use_smooth = True
    return details


def make_armature() -> bpy.types.Object:
    armature_data = bpy.data.armatures.new("GaryQuadrupedRig")
    rig = bpy.data.objects.new("GaryRig", armature_data)
    bpy.context.collection.objects.link(rig)
    select_only([rig])
    bpy.context.view_layer.objects.active = rig
    bpy.ops.object.mode_set(mode="EDIT")

    def bone(name: str, head: Sequence[float], tail: Sequence[float], parent: str | None = None, connected: bool = False):
        item = armature_data.edit_bones.new(name)
        item.head = head
        item.tail = tail
        if parent:
            item.parent = armature_data.edit_bones[parent]
            item.use_connect = connected
        return item

    bone("Root", (0, 0, .02), (0, 0, .22))
    bone("Pelvis", (0, -.72, 1.18), (0, -.23, 1.35), "Root")
    bone("Spine", (0, -.23, 1.35), (0, .38, 1.47), "Pelvis", True)
    bone("Chest", (0, .38, 1.47), (0, .92, 1.58), "Spine", True)
    bone("Neck", (0, .92, 1.58), (0, 1.45, 1.73), "Chest", True)
    bone("Head", (0, 1.45, 1.73), (0, 2.43, 1.65), "Neck", True)
    bone("Tail", (0, -1.10, 1.32), (0, -1.53, 1.23), "Pelvis")
    for side, x in (("L", .53), ("R", -.53)):
        bone(f"ForeUpper.{side}", (x, .69, 1.42), (x, .75, .82), "Chest")
        bone(f"ForeLower.{side}", (x, .75, .82), (x, .80, .28), f"ForeUpper.{side}", True)
        bone(f"ForePaw.{side}", (x, .80, .28), (x, 1.16, .13), f"ForeLower.{side}", True)
        bone(f"HindUpper.{side}", (x, -.76, 1.30), (x, -.79, .75), "Pelvis")
        bone(f"HindLower.{side}", (x, -.79, .75), (x, -.61, .29), f"HindUpper.{side}", True)
        bone(f"HindPaw.{side}", (x, -.61, .29), (x, -.08, .13), f"HindLower.{side}", True)
    bpy.ops.object.mode_set(mode="OBJECT")
    rig.show_in_front = True
    rig["asset_id"] = ASSET_ID
    rig["skeleton_contract"] = "quadruped-v1"
    return rig


def apply_authored_dimensions(objects: Sequence[bpy.types.Object]) -> None:
    """Scale the sculpt from convenient working coordinates to adult meters."""
    world_scale = Matrix.Diagonal((.86, .70, .78, 1.0))
    for obj in objects:
        obj.matrix_world = world_scale @ obj.matrix_world
        select_only([obj])
        bpy.context.view_layer.objects.active = obj
        bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)


def point_segment_distance(point: Vector, start: Vector, end: Vector) -> float:
    delta = end - start
    if delta.length_squared <= 1e-12:
        return (point - start).length
    t = max(0.0, min(1.0, (point - start).dot(delta) / delta.length_squared))
    return (point - (start + delta * t)).length


def skin_object(obj: bpy.types.Object, rig: bpy.types.Object, rigid_bone: str | None = None) -> None:
    for group in list(obj.vertex_groups):
        obj.vertex_groups.remove(group)
    groups = {bone.name: obj.vertex_groups.new(name=bone.name) for bone in rig.data.bones}
    if rigid_bone:
        groups[rigid_bone].add([vertex.index for vertex in obj.data.vertices], 1.0, "REPLACE")
    else:
        segments = {bone.name: (bone.head_local.copy(), bone.tail_local.copy()) for bone in rig.data.bones}
        to_rig = rig.matrix_world.inverted() @ obj.matrix_world

        def smoothstep(edge0: float, edge1: float, value: float) -> float:
            amount = max(0.0, min(1.0, (value - edge0) / (edge1 - edge0)))
            return amount * amount * (3.0 - 2.0 * amount)

        def inverse_distance_weights(point: Vector, names: Sequence[str]) -> Dict[str, float]:
            distances = ((name, point_segment_distance(point, *segments[name])) for name in names)
            weighted = [(name, 1.0 / max(distance, .035) ** 2.35) for name, distance in distances]
            total = sum(weight for _, weight in weighted)
            return {name: weight / total for name, weight in weighted}

        def renormalize(weights: Dict[str, float]) -> Dict[str, float]:
            total = sum(weights.values())
            return {name: value / total for name, value in weights.items() if value > 1e-8}

        def anchored_pair(value: float, anchors: Sequence[tuple[float, str]]) -> Dict[str, float]:
            if value <= anchors[0][0]:
                return {anchors[0][1]: 1.0}
            if value >= anchors[-1][0]:
                return {anchors[-1][1]: 1.0}
            for (start, start_name), (end, end_name) in zip(anchors, anchors[1:]):
                if start <= value <= end:
                    amount = smoothstep(start, end, value)
                    return {start_name: 1.0 - amount, end_name: amount}
            raise AssertionError("anchor interval not found")

        for vertex in obj.data.vertices:
            # Joined sculpt meshes retain the active volume's translated
            # object origin.  Bone rest coordinates are armature-local, so a
            # raw vertex.co comparison assigned the muzzle near the spine and
            # the paws/head to unrelated chains.  Always compare in one space.
            p = to_rig @ vertex.co
            if obj.name == "Claws":
                region = "Fore" if p.y > .35 else "Hind"
                side = "L" if p.x >= 0 else "R"
                groups[f"{region}Paw.{side}"].add([vertex.index], 1.0, "REPLACE")
                continue

            if obj.name == "Body":
                # The torso begins with a stable two-bone longitudinal field.
                # It never borrows from a limb, so left/right chains cannot
                # split the belly or create a serrated flank under motion.
                normalized = anchored_pair(
                    p.y,
                    (
                        (-1.42, "Tail"),
                        (-.72, "Pelvis"),
                        (-.18, "Spine"),
                        (.48, "Chest"),
                        (1.05, "Neck"),
                        # Reach rigid Head before the embedded ear/cranium
                        # inserts so those authored details cannot drift from
                        # the continuous skin in a deep forage pose.
                        (1.38, "Head"),
                    ),
                )

                # Same-side limb activation is continuous through shoulder or
                # hip and becomes complete below the body barrel. The high
                # attachment retains an axial share so the axilla/groin never
                # shears away from the torso.
                lateral = max(smoothstep(.20, .45, abs(p.x)), 1.0 - smoothstep(.46, .76, p.z))
                # High shoulder/hip skin remains primarily axial; articulated
                # influence ramps to full only below the body barrel. This
                # keeps the limb mobile without folding the neck-side surface
                # when the foreleg swings through the gait.
                attachment_cap = .15 + .85 * (1.0 - smoothstep(.64, .92, p.z))
                # High forelimb influence stops behind the cranium. Distal paw
                # skin may extend farther forward, so only the below-barrel
                # field retains that reach toward the toes.
                fore_reach = max(
                    1.0 - smoothstep(1.00, 1.16, p.y),
                    1.0 - smoothstep(.48, .78, p.z),
                )
                fore_band = smoothstep(.20, .58, p.y) * fore_reach
                hind_band = smoothstep(.20, .58, -p.y) * (1.0 - smoothstep(1.10, 1.34, -p.y))
                fore_activation = fore_band * lateral * attachment_cap
                hind_activation = hind_band * lateral * attachment_cap
                limb_activation = max(fore_activation, hind_activation)

                if limb_activation > 0.0:
                    side = "L" if p.x >= 0.0 else "R"
                    if fore_activation >= hind_activation:
                        # Exactly two adjacent forelimb segments. ForePaw has
                        # zero influence above the carpal zone; ForeLower has
                        # zero influence above its elbow transition.
                        chain = anchored_pair(
                            p.z,
                            ((.16, f"ForePaw.{side}"), (.38, f"ForeLower.{side}"), (.82, f"ForeUpper.{side}")),
                        )
                    else:
                        # Exactly two adjacent hindlimb segments. HindPaw has
                        # zero influence above the ankle/hock zone.
                        chain = anchored_pair(
                            p.z,
                            ((.16, f"HindPaw.{side}"), (.34, f"HindLower.{side}"), (.76, f"HindUpper.{side}")),
                        )
                    normalized = {name: value * (1.0 - limb_activation) for name, value in normalized.items()}
                    for name, value in chain.items():
                        normalized[name] = normalized.get(name, 0.0) + value * limb_activation

                # The longitudinal anchors already reach a rigid Head field
                # before the cranium/muzzle and blend continuously through the
                # neck. Do not add a conditional z/x head override here: that
                # former hard boundary inverted triangles along the lower
                # neck during the deep forage pose.
                target = None
                lock = 0.0

                # Lock the distal plantigrade paw and toe web to its paw bone,
                # but retain a smooth influence transition through the carpal
                # or hock. This prevents toe fins in deep head/weight shifts.
                if abs(p.x) > .25 and p.z < .40:
                    paw_lock = 1.0 - smoothstep(.18, .38, p.z)
                    if paw_lock > lock:
                        region = "Fore" if p.y > .35 else "Hind"
                        side = "L" if p.x >= 0 else "R"
                        target = f"{region}Paw.{side}"
                        lock = paw_lock

                if target and lock > 0:
                    normalized = {name: value * (1.0 - lock) for name, value in normalized.items()}
                    normalized[target] = normalized.get(target, 0.0) + lock
            else:
                normalized = inverse_distance_weights(p, [name for name in segments if name != "Root"])

            # glTF's stable contract permits at most four joint influences.
            strongest = sorted(normalized.items(), key=lambda item: item[1], reverse=True)[:4]
            strongest_total = sum(weight for _, weight in strongest)
            for name, weight in strongest:
                groups[name].add([vertex.index], weight / strongest_total, "REPLACE")
    modifier = obj.modifiers.new("GaryQuadrupedRig", "ARMATURE")
    modifier.object = rig
    obj.parent = rig
    obj.matrix_parent_inverse = rig.matrix_world.inverted()


def reset_pose(rig: bpy.types.Object) -> None:
    for bone in rig.pose.bones:
        bone.rotation_mode = "XYZ"
        bone.location = (0, 0, 0)
        bone.rotation_euler = (0, 0, 0)
        bone.scale = (1, 1, 1)


def finish_action(action: bpy.types.Action, interpolation: str = "BEZIER") -> bpy.types.Action:
    for curve in action.fcurves:
        for point in curve.keyframe_points:
            point.interpolation = interpolation
    action.use_fake_user = True
    return action


def action_begin(rig: bpy.types.Object, name: str) -> bpy.types.Action:
    reset_pose(rig)
    action = bpy.data.actions.new(name)
    rig.animation_data_create()
    rig.animation_data.action = action
    return action


def key_bone(rig: bpy.types.Object, bone_name: str, frame: int, *, rotation=None, location=None, scale=None, group: str):
    bone = rig.pose.bones[bone_name]
    bone.rotation_mode = "XYZ"
    if rotation is not None:
        bone.rotation_euler = rotation
        bone.keyframe_insert("rotation_euler", frame=frame, group=group)
    if location is not None:
        bone.location = location
        bone.keyframe_insert("location", frame=frame, group=group)
    if scale is not None:
        bone.scale = scale
        bone.keyframe_insert("scale", frame=frame, group=group)


def make_idle(rig: bpy.types.Object) -> bpy.types.Action:
    name = "BearIdle"
    action = action_begin(rig, name)
    for frame, breath, sway in ((1, 0.0, 0.0), (30, .012, .012), (60, 0.0, 0.0), (90, .010, -.012), (120, 0.0, 0.0)):
        key_bone(rig, "Root", frame, location=(0, 0, 0), group=name)
        key_bone(rig, "Chest", frame, scale=(1 + breath * .35, 1 + breath * .55, 1 + breath), rotation=(0, 0, sway), group=name)
        key_bone(rig, "Head", frame, rotation=(math.radians(sway * 45), 0, sway * .55), group=name)
        key_bone(rig, "Tail", frame, rotation=(0, math.radians(3) * math.sin(frame / 25), 0), group=name)
    return finish_action(action, "BEZIER")


def make_walk(rig: bpy.types.Object) -> bpy.types.Action:
    name = "BearWalk"
    action = action_begin(rig, name)
    # A heavy diagonal quadruped walk: LF/RH oppose RF/LH. Paw counter-rotation
    # keeps planted feet flatter around contact instead of skating visibly.
    for frame, phase in ((1, 0.0), (10, math.pi / 2), (19, math.pi), (28, math.pi * 1.5), (37, math.tau)):
        stride = math.cos(phase)
        bounce = (1.0 - math.cos(phase * 2)) * .008
        key_bone(rig, "Root", frame, location=(math.sin(phase) * .006, 0, bounce), group=name)
        key_bone(rig, "Pelvis", frame, rotation=(0, 0, stride * math.radians(.8)), group=name)
        key_bone(rig, "Spine", frame, rotation=(0, 0, -stride * math.radians(.65)), group=name)
        key_bone(rig, "Head", frame, rotation=(math.sin(phase * 2) * math.radians(.7), 0, -stride * math.radians(.35)), group=name)
        for side, side_offset in (("L", 0.0), ("R", math.pi)):
            fore = math.cos(phase + side_offset)
            hind = -fore
            key_bone(rig, f"ForeUpper.{side}", frame, rotation=(fore * math.radians(7), 0, 0), group=name)
            key_bone(rig, f"ForeLower.{side}", frame, rotation=(-max(0, -fore) * math.radians(5), 0, 0), group=name)
            key_bone(rig, f"ForePaw.{side}", frame, rotation=(-fore * math.radians(3), 0, 0), group=name)
            key_bone(rig, f"HindUpper.{side}", frame, rotation=(hind * math.radians(6), 0, 0), group=name)
            key_bone(rig, f"HindLower.{side}", frame, rotation=(-max(0, -hind) * math.radians(7), 0, 0), group=name)
            key_bone(rig, f"HindPaw.{side}", frame, rotation=(-hind * math.radians(3), 0, 0), group=name)
    return finish_action(action, "LINEAR")


def make_forage(rig: bpy.types.Object) -> bpy.types.Action:
    name = "BearForage"
    action = action_begin(rig, name)
    for frame, amount, sweep in ((1, 0.0, 0.0), (36, 1.0, -.35), (72, .92, .45), (108, 1.0, -.28), (144, 0.0, 0.0)):
        key_bone(rig, "Root", frame, location=(0, 0, 0), group=name)
        key_bone(rig, "Spine", frame, rotation=(-amount * math.radians(2), 0, sweep * math.radians(1.5)), group=name)
        key_bone(rig, "Chest", frame, rotation=(-amount * math.radians(4), 0, sweep * math.radians(2.5)), group=name)
        key_bone(rig, "Neck", frame, rotation=(-amount * math.radians(16), 0, sweep * math.radians(7)), group=name)
        key_bone(rig, "Head", frame, rotation=(-amount * math.radians(24), 0, sweep * math.radians(12)), group=name)
        for side in ("L", "R"):
            key_bone(rig, f"ForeUpper.{side}", frame, rotation=(-amount * math.radians(2.5), 0, 0), group=name)
    return finish_action(action, "BEZIER")


def make_turn(rig: bpy.types.Object) -> bpy.types.Action:
    name = "BearTurn"
    action = action_begin(rig, name)
    for frame, amount in ((1, 0.0), (22, .48), (45, 1.0), (68, .48), (90, 0.0)):
        key_bone(rig, "Root", frame, location=(0, 0, 0), group=name)
        key_bone(rig, "Pelvis", frame, rotation=(0, 0, amount * math.radians(5)), group=name)
        key_bone(rig, "Spine", frame, rotation=(0, 0, amount * math.radians(9)), group=name)
        key_bone(rig, "Chest", frame, rotation=(0, 0, amount * math.radians(11)), group=name)
        key_bone(rig, "Neck", frame, rotation=(0, 0, amount * math.radians(15)), group=name)
        key_bone(rig, "Head", frame, rotation=(0, 0, amount * math.radians(18)), group=name)
        for side, sign in (("L", 1), ("R", -1)):
            key_bone(rig, f"ForeUpper.{side}", frame, rotation=(sign * amount * math.radians(4), 0, 0), group=name)
            key_bone(rig, f"HindUpper.{side}", frame, rotation=(-sign * amount * math.radians(3), 0, 0), group=name)
    return finish_action(action, "BEZIER")


def install_animation_tracks(rig: bpy.types.Object, actions: Sequence[bpy.types.Action]) -> None:
    rig.animation_data_create()
    rig.animation_data.action = None
    for existing in list(rig.animation_data.nla_tracks):
        rig.animation_data.nla_tracks.remove(existing)
    for action in actions:
        track = rig.animation_data.nla_tracks.new()
        track.name = action.name
        strip = track.strips.new(action.name, int(action.frame_range[0]), action)
        strip.action_frame_start = action.frame_range[0]
        strip.action_frame_end = action.frame_range[1]
        strip.use_auto_blend = False
    reset_pose(rig)


def merge_detail_category(objects: Sequence[bpy.types.Object], name: str) -> bpy.types.Object:
    select_only(objects)
    bpy.context.view_layer.objects.active = objects[0]
    bpy.ops.object.join()
    result = bpy.context.object
    result.name = name
    return result


def duplicate_lod(meshes: Sequence[bpy.types.Object], rig: bpy.types.Object, ratio: float) -> Tuple[List[bpy.types.Object], bpy.types.Object]:
    select_only(list(meshes) + [rig])
    bpy.ops.object.duplicate()
    duplicates = list(bpy.context.selected_objects)
    lod_rig = next(obj for obj in duplicates if obj.type == "ARMATURE")
    lod_rig.name = "GaryRig.LOD2"
    lod_meshes = [obj for obj in duplicates if obj.type == "MESH"]
    for obj in lod_meshes:
        obj.name = f"{obj.name}.LOD2"
        obj.data.name = "GaryContinuousAnatomicalSkinLOD2" if obj.name.startswith("Body") else f"{obj.name.removesuffix('.LOD2')}LOD2"
        obj.parent = lod_rig
        for modifier in list(obj.modifiers):
            if modifier.type == "ARMATURE":
                obj.modifiers.remove(modifier)
        if len(obj.data.polygons) > 1000:
            modifier = obj.modifiers.new("Silhouette-aware LOD2 decimation", "DECIMATE")
            modifier.decimate_type = "COLLAPSE"
            modifier.ratio = ratio
            modifier.use_collapse_triangulate = True
            modifier.use_symmetry = True
            apply_modifiers(obj)
            limit_vertex_influences(obj, 4)
        armature = obj.modifiers.new("GaryQuadrupedRig", "ARMATURE")
        armature.object = lod_rig
    return lod_meshes, lod_rig


def limit_vertex_influences(obj: bpy.types.Object, limit: int) -> None:
    """Normalize decimator-interpolated weights to the glTF four-joint cap."""
    for vertex in obj.data.vertices:
        assignments = sorted(
            ((item.group, item.weight) for item in vertex.groups if item.weight > 1e-8),
            key=lambda item: item[1],
            reverse=True,
        )
        if not assignments:
            continue
        kept = assignments[:limit]
        removed = assignments[limit:]
        for group_index, _ in removed:
            obj.vertex_groups[group_index].remove([vertex.index])
        total = sum(weight for _, weight in kept)
        for group_index, weight in kept:
            obj.vertex_groups[group_index].add([vertex.index], weight / total, "REPLACE")


def triangulate(meshes: Sequence[bpy.types.Object]) -> None:
    for obj in meshes:
        # Triangulate the source mesh without applying the armature modifier.
        # Applying the whole modifier stack would bake the rest pose and strip
        # JOINTS_0/WEIGHTS_0 from the exported asset.
        mesh = bmesh.new()
        mesh.from_mesh(obj.data)
        bmesh.ops.triangulate(mesh, faces=list(mesh.faces))
        mesh.to_mesh(obj.data)
        mesh.free()
        obj.data.update()
        for polygon in obj.data.polygons:
            polygon.use_smooth = True


def gltf_export(filepath: Path, objects: Sequence[bpy.types.Object]) -> None:
    select_only(objects)
    kwargs = dict(
        filepath=str(filepath),
        export_format="GLB",
        use_selection=True,
        export_yup=True,
        export_apply=False,
        export_texcoords=True,
        export_normals=True,
        export_tangents=True,
        export_materials="EXPORT",
        export_colors=False,
        export_cameras=False,
        export_lights=False,
        export_skins=True,
        export_def_bones=True,
        export_animations=True,
        export_frame_range=True,
        export_force_sampling=False,
        export_nla_strips=True,
        export_optimize_animation_size=True,
        export_draco_mesh_compression_enable=True,
        export_draco_mesh_compression_level=6,
        export_draco_position_quantization=14,
        export_draco_normal_quantization=10,
        export_draco_texcoord_quantization=12,
        export_draco_generic_quantization=12,
        export_extras=True,
    )
    try:
        bpy.ops.export_scene.gltf(**kwargs)
    except TypeError:
        for optional in ("export_force_sampling", "export_optimize_animation_size", "export_nla_strips"):
            kwargs.pop(optional, None)
        bpy.ops.export_scene.gltf(**kwargs)


def object_bounds(obj: bpy.types.Object) -> Tuple[Vector, Vector]:
    corners = [obj.matrix_world @ Vector(corner) for corner in obj.bound_box]
    return Vector((min(p.x for p in corners), min(p.y for p in corners), min(p.z for p in corners))), Vector((max(p.x for p in corners), max(p.y for p in corners), max(p.z for p in corners)))


def render_preview(meshes: Sequence[bpy.types.Object], body: bpy.types.Object, preview_dir: Path) -> Path:
    preview_dir.mkdir(parents=True, exist_ok=True)
    output = preview_dir / f"{ASSET_ID}.png"
    scene = bpy.context.scene
    low, high = object_bounds(body)
    center = (low + high) * .5
    # Three-quarter front view makes limb attachment, paw grounding, muzzle and
    # body taper legible in one production-gate image.
    bpy.ops.object.camera_add(location=(5.3, 6.6, 3.0))
    camera = bpy.context.object
    camera.name = "GaryPreviewCamera"
    camera.rotation_euler = (Vector((0, .45, 1.08)) - camera.location).to_track_quat("-Z", "Y").to_euler()
    camera.data.lens = 62
    scene.camera = camera

    def area(name, location, energy, size, color):
        bpy.ops.object.light_add(type="AREA", location=location)
        light = bpy.context.object
        light.name = name
        light.data.energy = energy
        light.data.size = size
        light.data.color = color
        light.rotation_euler = (center - light.location).to_track_quat("-Z", "Y").to_euler()
        return light

    lights = [
        area("ArcticKey", (-3.4, 4.3, 5.1), 420, 3.2, (1.0, .87, .74)),
        area("SkyFill", (3.3, 1.2, 3.4), 270, 3.0, (.63, .80, 1.0)),
        area("Rim", (-1.4, -3.2, 3.5), 390, 2.4, (.72, .91, 1.0)),
    ]
    bpy.ops.mesh.primitive_plane_add(size=14, location=(0, 0, .015))
    floor = bpy.context.object
    floor.name = "PreviewGround"
    floor.data.materials.append(simple_material("PreviewGround", (.025, .038, .045, 1), .72))

    # This is a material gate, not only a silhouette render: Eevee verifies the
    # exact image-texture nodes exported to glTF, including directional fur
    # albedo, roughness and tangent-space normal response.
    scene.render.engine = "BLENDER_EEVEE"
    scene.eevee.taa_render_samples = 48
    scene.eevee.use_gtao = True
    scene.eevee.gtao_distance = 3.0
    scene.eevee.gtao_factor = 1.25
    scene.render.resolution_x = 1200
    scene.render.resolution_y = 900
    scene.render.resolution_percentage = 100
    scene.render.image_settings.file_format = "PNG"
    scene.render.film_transparent = False
    scene.world.use_nodes = True
    background = scene.world.node_tree.nodes.get("Background")
    background.inputs["Color"].default_value = (.012, .019, .027, 1)
    background.inputs["Strength"].default_value = .22
    scene.render.filepath = str(output)
    scene.view_settings.look = "Medium High Contrast"
    scene.view_settings.exposure = -0.35
    bpy.ops.render.render(write_still=True)
    for obj in [camera, floor, *lights]:
        bpy.data.objects.remove(obj, do_unlink=True)
    return output


def mesh_stats(meshes: Sequence[bpy.types.Object]) -> Dict[str, int]:
    for obj in meshes:
        obj.data.calc_loop_triangles()
    return {
        "meshes": len(meshes),
        "vertices": sum(len(obj.data.vertices) for obj in meshes),
        "triangles": sum(len(obj.data.loop_triangles) for obj in meshes),
        "materials": len({slot.material.name for obj in meshes for slot in obj.material_slots if slot.material}),
    }


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def glb_json(path: Path) -> Dict:
    with path.open("rb") as handle:
        magic, version, length = struct.unpack("<4sII", handle.read(12))
        if magic != b"glTF" or version != 2:
            raise RuntimeError(f"{path} is not glTF 2.0")
        while handle.tell() < length:
            chunk_length, chunk_type = struct.unpack("<II", handle.read(8))
            data = handle.read(chunk_length)
            if chunk_type == 0x4E4F534A:
                return json.loads(data.decode("utf-8"))
    raise RuntimeError(f"{path} does not contain a JSON chunk")


def verify_glb(path: Path) -> Dict[str, object]:
    data = glb_json(path)
    animations = [animation.get("name") for animation in data.get("animations", [])]
    missing = [name for name in CLIP_NAMES if name not in animations]
    if missing:
        raise RuntimeError(f"{path.name} is missing authored clips: {missing}; found {animations}")
    if not data.get("skins"):
        raise RuntimeError(f"{path.name} has no skin")
    if not any(primitive.get("attributes", {}).get("JOINTS_0") is not None for mesh in data.get("meshes", []) for primitive in mesh.get("primitives", [])):
        raise RuntimeError(f"{path.name} has no JOINTS_0 attribute")
    if not any(material.get("normalTexture") for material in data.get("materials", [])):
        raise RuntimeError(f"{path.name} has no normal-mapped material")
    triangles = 0
    vertices = 0
    for mesh in data.get("meshes", []):
        for primitive in mesh.get("primitives", []):
            triangles += data["accessors"][primitive["indices"]]["count"] // 3
            vertices += data["accessors"][primitive["attributes"]["POSITION"]]["count"]
    return {
        "animations": animations,
        "skins": len(data.get("skins", [])),
        "nodes": len(data.get("nodes", [])),
        "embeddedImages": len(data.get("images", [])),
        "triangles": triangles,
        "vertices": vertices,
    }


def main() -> None:
    args = parse_args()
    args.output = args.output.resolve()
    args.source = args.source.resolve()
    if args.preview:
        args.preview = args.preview.resolve()
    args.output.mkdir(parents=True, exist_ok=True)
    purge_scene()
    scene = bpy.context.scene
    scene.render.fps = 30
    scene.unit_settings.system = "METRIC"
    scene.unit_settings.scale_length = 1.0

    texture_paths = write_texture_set(args.source, args.texture_size)
    runtime_texture_paths = make_runtime_texture_set(texture_paths)
    materials = {
        "fur": make_fur_material(runtime_texture_paths),
        "eyes": simple_material("GaryEyes", (.012, .009, .006, 1), .12),
        "nose": simple_material("GaryNose", (.018, .021, .019, 1), .34),
        "mouth": simple_material("GaryMouth", (.035, .020, .018, 1), .46),
        "inner_ear": simple_material("GaryInnerEar", (.24, .16, .14, 1), .82),
        "claw": simple_material("GaryClawKeratin", (.105, .095, .075, 1), .66),
    }
    body = make_body(args.voxel_size)
    smart_uv(body)
    body.data.materials.append(materials["fur"])
    details = make_details(materials)
    rig = make_armature()
    apply_authored_dimensions([body, *details.values(), rig])
    skin_object(body, rig)
    skin_object(details["eyes"], rig, "Head")
    skin_object(details["nose"], rig, "Head")
    skin_object(details["inner_ears"], rig, "Head")
    skin_object(details["mouth"], rig, "Head")
    # The claws are rigid in four groups only after splitting them would cost
    # four draw calls. Body-derived inverse-distance weights correctly select
    # each paw bone while retaining one claw mesh.
    skin_object(details["claws"], rig)

    actions = [make_idle(rig), make_walk(rig), make_forage(rig), make_turn(rig)]
    install_animation_tracks(rig, actions)
    meshes = [body, *details.values()]
    triangulate(meshes)

    preview_path = render_preview(meshes, body, args.preview) if args.preview else None

    lod2_meshes, lod2_rig = duplicate_lod(meshes, rig, .34)
    # Duplicated armature keeps NLA action tracks; enforce the same pose/clip set.
    triangulate(lod2_meshes)
    lod0_path = args.output / f"{ASSET_ID}-lod0.glb"
    lod2_path = args.output / f"{ASSET_ID}-lod2.glb"
    gltf_export(lod0_path, [*meshes, rig])
    gltf_export(lod2_path, [*lod2_meshes, lod2_rig])

    lod0_stats = mesh_stats(meshes)
    lod2_stats = mesh_stats(lod2_meshes)
    low, high = object_bounds(body)
    dimensions = high - low
    manifest = {
        "schemaVersion": 1,
        "id": ASSET_ID,
        "displayName": "Gary",
        "species": "Ursus maritimus",
        "license": "Original-Project-Asset",
        "generator": "tools/animal-pipeline/build_gary.py",
        "provenance": {
            "geometry": "Original procedural sculpt authored and fused in Blender by this repository pipeline; no third-party geometry.",
            "textures": "Original deterministic NumPy-generated fur PBR maps; no source texture pixels.",
            "referencePolicy": "Wildlife photographs used only for visual proportion study.",
            "visualReferences": [
                "https://www.fws.gov/media/polar-bear-walking-ice",
                "https://animals.sandiegozoo.org/animals/polar-bear",
            ],
        },
        "coordinateSystem": {"unit": "meter", "up": "+Y", "forward": "-Z", "origin": "ground-under-torso"},
        "dimensionsMeters": {"width": round(dimensions.x, 3), "length": round(dimensions.y, 3), "height": round(dimensions.z, 3)},
        "skeleton": {
            "name": "GaryQuadrupedRig",
            "bones": [bone.name for bone in rig.data.bones],
            "maxInfluences": 4,
        },
        "clips": [{"name": name} for name in CLIP_NAMES],
        "materials": ["GaryPolarBearFur", "GaryEyes", "GaryNose", "GaryMouth", "GaryInnerEar", "GaryClawKeratin"],
        "maps": {
            name: {
                "kind": name,
                "sourceFile": str(path.relative_to(Path.cwd())),
                "embeddedImageName": f"{ASSET_ID}-{name}",
                "runtimeMimeType": "image/png" if name == "roughness" else "image/jpeg",
                "runtimeEncoding": "1024px glTF packed PNG" if name == "roughness" else "2048px JPEG quality 90 (Blender image output)",
                "width": args.texture_size,
                "height": args.texture_size,
                "bytes": path.stat().st_size,
                "sha256": file_sha256(path),
            }
            for name, path in texture_paths.items()
        },
        "lod0": {
            "file": lod0_path.name, "bytes": lod0_path.stat().st_size, "sha256": file_sha256(lod0_path),
            **lod0_stats, **verify_glb(lod0_path),
        },
        "lod2": {
            "file": lod2_path.name, "bytes": lod2_path.stat().st_size, "sha256": file_sha256(lod2_path),
            **lod2_stats, **verify_glb(lod2_path),
        },
        "preview": str(preview_path) if preview_path else None,
    }
    manifest_path = args.source / f"{ASSET_ID}.asset.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    if args.keep_blend:
        args.source.mkdir(parents=True, exist_ok=True)
        # Editable source retains lossless PNG references; runtime GLBs above
        # have already embedded their compressed delivery copies.
        relink_fur_material(materials["fur"], texture_paths)
        bpy.context.preferences.filepaths.save_version = 0
        bpy.ops.wm.save_as_mainfile(filepath=str(args.source / f"{ASSET_ID}-source.blend"))
    print(json.dumps(manifest, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
