#!/usr/bin/env python3
"""Build the project's original authored California sea lion.

The geometry, UVs, PBR maps, skeleton and animation curves are generated by
this repository script.  Wildlife photography is used only to study anatomy;
no third-party mesh, texture pixel, rig or clip enters the asset.

Run with Blender 3.4 or newer:

  /Applications/Blender.app/Contents/MacOS/Blender \
    --background --factory-startup \
    --python tools/animal-pipeline/build_sea_lion.py -- \
    --output public/game/animals/authored \
    --source tools/animal-pipeline/source \
    --preview /private/tmp/sloth-sea-lion-previews --keep-blend
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import math
import struct
import sys
import tempfile
from pathlib import Path
from typing import Dict, Iterable, List, Sequence, Tuple

import bpy
import bmesh
import numpy as np
from mathutils import Vector


ASSET_ID = "california-sea-lion"
CLIP_NAMES = ("SeaLionIdle", "SeaLionSwim", "SeaLionSurface", "SeaLionDive")
TEXTURE_SIZE = 2048


def parse_args() -> argparse.Namespace:
    argv = sys.argv[sys.argv.index("--") + 1 :] if "--" in sys.argv else []
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--source", type=Path, default=Path(__file__).resolve().parent / "source")
    parser.add_argument("--preview", type=Path)
    parser.add_argument("--keep-blend", action="store_true")
    parser.add_argument("--texture-size", type=int, default=TEXTURE_SIZE)
    parser.add_argument("--voxel-size", type=float, default=.0152)
    return parser.parse_args(argv)


def ensure_object_mode() -> None:
    if bpy.context.object and bpy.context.object.mode != "OBJECT":
        bpy.ops.object.mode_set(mode="OBJECT")


def select_only(objects: Iterable[bpy.types.Object]) -> None:
    ensure_object_mode()
    bpy.ops.object.select_all(action="DESELECT")
    active = None
    for obj in objects:
        obj.hide_set(False)
        obj.hide_viewport = False
        obj.hide_render = False
        obj.select_set(True)
        active = obj
    if active:
        bpy.context.view_layer.objects.active = active


def purge() -> None:
    ensure_object_mode()
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)
    for datablocks in (
        bpy.data.meshes, bpy.data.curves, bpy.data.armatures, bpy.data.materials,
        bpy.data.images, bpy.data.actions, bpy.data.textures,
    ):
        for item in list(datablocks):
            if item.users == 0:
                datablocks.remove(item)


def apply_modifier(obj: bpy.types.Object, name: str) -> None:
    select_only([obj])
    bpy.context.view_layer.objects.active = obj
    bpy.ops.object.modifier_apply(modifier=name)


def add_volume(
    name: str,
    location: Sequence[float],
    scale: Sequence[float],
    rotation: Sequence[float] = (0, 0, 0),
    subdivisions: int = 2,
) -> bpy.types.Object:
    bpy.ops.mesh.primitive_ico_sphere_add(subdivisions=subdivisions, radius=1, location=location)
    obj = bpy.context.object
    obj.name = f"SculptVolume.{name}"
    obj.scale = scale
    obj.rotation_euler = rotation
    select_only([obj])
    bpy.ops.object.transform_apply(location=False, rotation=True, scale=True)
    return obj


def create_loft_volume(name: str) -> bpy.types.Object:
    """Create a closed cross-section loft for the entire axial animal.

    Unlike an ellipsoid blockout, these rings establish one deliberate dorsal
    and ventral line from hindquarters through the canine skull and muzzle.
    """
    sections = (
        (-1.12, .45, .12, .12), (-1.02, .48, .25, .20),
        (-.84, .54, .34, .27), (-.58, .61, .42, .32),
        (-.30, .67, .47, .35), (.02, .72, .49, .37),
        (.30, .78, .47, .38), (.52, .87, .43, .37),
        (.70, .96, .38, .34), (.87, 1.05, .33, .29),
        (1.04, 1.12, .29, .25), (1.20, 1.17, .27, .215),
        (1.34, 1.17, .235, .175), (1.47, 1.15, .195, .145),
        (1.59, 1.13, .150, .110), (1.70, 1.13, .090, .072),
    )
    radial = 64
    vertices: List[Tuple[float, float, float]] = []
    for y, center_z, radius_x, radius_z in sections:
        for index in range(radial):
            angle = math.tau * index / radial
            # The slightly compressed ventral half preserves a long fusiform
            # silhouette instead of the spherical belly of the blockout.
            sine = math.sin(angle)
            z_scale = radius_z * (.94 if sine < 0 else 1.0)
            vertices.append((radius_x * math.cos(angle), y, center_z + z_scale * sine))
    faces: List[Tuple[int, ...]] = []
    for section in range(len(sections) - 1):
        a = section * radial
        b = (section + 1) * radial
        for index in range(radial):
            nxt = (index + 1) % radial
            faces.append((a + index, b + index, b + nxt, a + nxt))
    rear = len(vertices)
    vertices.append((0, sections[0][0], sections[0][1]))
    front = len(vertices)
    vertices.append((0, sections[-1][0], sections[-1][1]))
    for index in range(radial):
        nxt = (index + 1) % radial
        faces.append((rear, nxt, index))
        last = (len(sections) - 1) * radial
        faces.append((front, last + index, last + nxt))
    mesh = bpy.data.meshes.new(f"{name}Mesh")
    mesh.from_pydata(vertices, [], faces)
    mesh.update()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(obj)
    return obj


def create_blade_volume(name: str, outline: Sequence[Tuple[float, float, float, float]]) -> bpy.types.Object:
    """Create a closed tapered flipper blade with explicit root thickness."""
    vertices = [(x, y, z + thickness * .5) for x, y, z, thickness in outline]
    vertices += [(x, y, z - thickness * .5) for x, y, z, thickness in outline]
    count = len(outline)
    faces: List[Tuple[int, ...]] = [tuple(range(count)), tuple(reversed(range(count, count * 2)))]
    for index in range(count):
        nxt = (index + 1) % count
        faces.append((index, nxt, count + nxt, count + index))
    mesh = bpy.data.meshes.new(f"{name}Mesh")
    mesh.from_pydata(vertices, [], faces)
    mesh.update()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(obj)
    return obj


def carve_flipper_digit_channels(body: bpy.types.Object) -> None:
    """Sculpt shallow webbing channels directly into the continuous skin."""
    channels: List[Tuple[List[Vector], float, float]] = []
    for side, sign in (("L", 1), ("R", -1)):
        for digit in range(4):
            offset = (digit - 1.5) * .028
            channels.append((
                [Vector(point) for point in (
                    (sign * .49, .17 + offset, .668),
                    (sign * .65, .02 + offset * .55, .534),
                    (sign * .83, -.13 + offset * .25, .407),
                    (sign * .925, -.215 + offset * .10, .318),
                )],
                .040,
                .018,
            ))
        for digit in range(3):
            lateral = (digit - 1) * .018
            channels.append((
                [Vector(point) for point in (
                    (sign * .18, -1.20, .452),
                    (sign * (.32 + lateral), -1.46, .350),
                    (sign * (.48 + lateral * 1.5), -1.70, .272),
                    (sign * (.59 + lateral * 2), -1.84 + digit * .008, .220),
                )],
                .034,
                .014,
            ))
    for vertex in body.data.vertices:
        point = vertex.co.copy()
        inset = 0.0
        for points, width, depth in channels:
            distance = min(point_segment_distance(point, start, end) for start, end in zip(points, points[1:]))
            if distance < width:
                profile = 1 - distance / width
                inset = max(inset, depth * profile * profile)
        if inset:
            vertex.co.z -= inset
    body.data.update()


def create_continuous_skin(voxel_size: float) -> bpy.types.Object:
    """Build the clay-approved, watertight adult-male production skin.

    The anatomy module is an original repository source and deliberately has no
    production export side effects.  Keeping the accepted neutral-clay builder
    as the geometry authority prevents the hero GLBs from drifting back toward
    the rejected primitive-era silhouette.
    """
    anatomy_path = Path(__file__).with_name("build_sea_lion_clay_review.py")
    spec = importlib.util.spec_from_file_location("sloth_sea_lion_approved_anatomy", anatomy_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load approved sea-lion anatomy from {anatomy_path}")
    anatomy = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(anatomy)
    body = anatomy.build_anatomical_skin(voxel_size)
    body.name = "Body"
    body.data.name = "CaliforniaSeaLionContinuousAnatomicalSkin"
    body["source_geometry"] = "original-approved-axial-and-webbed-appendage-lofts"
    body["anatomy_gate"] = "sea-lion-clay-v4-approved"
    return body


def compact_haul_out_y(y: float) -> float:
    if y < -.65:
        return -.65 + (y + .65) * .82
    if y > .25:
        return .25 + (y - .25) * .82
    return y


def smart_uv(obj: bpy.types.Object) -> None:
    select_only([obj])
    bpy.context.view_layer.objects.active = obj
    bpy.ops.object.mode_set(mode="EDIT")
    bpy.ops.mesh.select_all(action="SELECT")
    bpy.ops.uv.smart_project(angle_limit=math.radians(50), island_margin=.012)
    bpy.ops.object.mode_set(mode="OBJECT")


def save_image(path: Path, pixels: np.ndarray) -> None:
    image = bpy.data.images.new(path.stem, width=pixels.shape[1], height=pixels.shape[0], alpha=True, float_buffer=False)
    image.pixels.foreach_set(np.flipud(pixels).reshape(-1))
    image.filepath_raw = str(path)
    image.file_format = "PNG"
    image.save()
    bpy.data.images.remove(image)


def filtered_noise(rng: np.random.Generator, size: int) -> Tuple[np.ndarray, np.ndarray]:
    fine = rng.normal(0, 1, (size, size)).astype(np.float32)
    for _ in range(3):
        fine = (fine * 2 + np.roll(fine, 1, 0) + np.roll(fine, -1, 0) + np.roll(fine, 1, 1) + np.roll(fine, -1, 1)) / 6
    fine /= max(float(fine.std()), 1e-6)
    u = np.linspace(0, 1, size, endpoint=False, dtype=np.float32)
    v = np.linspace(0, 1, size, endpoint=False, dtype=np.float32)
    xx, yy = np.meshgrid(u, v)
    broad = np.zeros_like(fine)
    for _ in range(17):
        angle = float(rng.uniform(0, math.tau))
        frequency = float(rng.uniform(1.5, 10))
        phase = float(rng.uniform(0, math.tau))
        broad += np.sin((xx * math.cos(angle) + yy * math.sin(angle)) * math.tau * frequency + phase)
    broad /= max(float(broad.std()), 1e-6)
    return fine, broad


def write_source_maps(source: Path, size: int) -> Dict[str, Path]:
    source.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(72590311)
    fine, broad = filtered_noise(rng, size)
    u = np.linspace(0, 1, size, endpoint=False, dtype=np.float32)
    v = np.linspace(0, 1, size, endpoint=False, dtype=np.float32)
    xx, yy = np.meshgrid(u, v)
    short_coat = (
        np.sin((xx * .24 + yy) * math.tau * 188 + broad * .38) * .52
        + np.sin((xx * -.17 + yy) * math.tau * 131 + fine * .20) * .23
    )
    wet_streak = np.sin(xx * math.tau * 23 + broad * .22)
    height = np.clip(fine * .28 + broad * .08 + short_coat * .54 + wet_streak * .025, -1, 1)

    # California sea lion hide: umber/charcoal with warm, irregular shoulder
    # highlights. This is generated color variation, not photographic pixels.
    base = np.array((.235, .135, .074), dtype=np.float32)
    # Keep albedo nearly uniform at UV-island scale. Large stochastic color
    # fields made smart-project seams read as jagged hide patches.
    warmth = np.full((*fine.shape, 1), .014, dtype=np.float32)
    value = np.clip(
        1 + fine[..., None] * .006 + short_coat[..., None] * .004,
        .96,
        1.04,
    )
    albedo = np.zeros((size, size, 4), dtype=np.float32)
    albedo[..., :3] = np.clip(base * value + warmth * np.array((.65, .30, .10), dtype=np.float32), 0, 1)
    albedo[..., 3] = 1

    gy, gx = np.gradient(height)
    nx, ny, nz = -gx * 1.15, -gy * 1.15, np.ones_like(gx)
    length = np.sqrt(nx * nx + ny * ny + nz * nz)
    normal = np.stack((nx / length * .5 + .5, ny / length * .5 + .5, nz / length * .5 + .5, np.ones_like(gx)), axis=-1)

    # Wet hide alternates slick highlights with rougher drying patches.
    rough_value = np.clip(.58 + fine * .011 - short_coat * .008, .52, .65)
    roughness = np.stack((rough_value, rough_value, rough_value, np.ones_like(rough_value)), axis=-1)
    paths = {
        "albedo": source / f"{ASSET_ID}-albedo.png",
        "normal": source / f"{ASSET_ID}-normal.png",
        "roughness": source / f"{ASSET_ID}-roughness.png",
    }
    for kind, pixels in (("albedo", albedo), ("normal", normal), ("roughness", roughness)):
        save_image(paths[kind], pixels)
    return paths


def make_runtime_maps(source_paths: Dict[str, Path]) -> Dict[str, Path]:
    directory = Path(tempfile.gettempdir()) / "sloth-sea-lion-runtime-textures"
    directory.mkdir(parents=True, exist_ok=True)
    result: Dict[str, Path] = {}
    for kind, source in source_paths.items():
        image = bpy.data.images.load(str(source), check_existing=False)
        _ = image.pixels[0]
        if kind == "roughness":
            image.scale(1024, 1024)
        target = directory / f"{ASSET_ID}-{kind}.{'png' if kind == 'roughness' else 'jpg'}"
        image.filepath_raw = str(target)
        image.file_format = "PNG" if kind == "roughness" else "JPEG"
        image.save()
        result[kind] = target
        bpy.data.images.remove(image)
    return result


def principled(material: bpy.types.Material):
    return material.node_tree.nodes.get("Principled BSDF")


def simple_material(name: str, color: Sequence[float], roughness: float, metallic: float = 0) -> bpy.types.Material:
    material = bpy.data.materials.new(name)
    material.use_nodes = True
    node = principled(material)
    node.inputs["Base Color"].default_value = tuple(color)
    node.inputs["Roughness"].default_value = roughness
    node.inputs["Metallic"].default_value = metallic
    if "Specular" in node.inputs:
        node.inputs["Specular"].default_value = .48
    return material


def make_skin_material(paths: Dict[str, Path]) -> bpy.types.Material:
    material = bpy.data.materials.new("CaliforniaSeaLionWetHide")
    material.use_nodes = True
    nodes = material.node_tree.nodes
    links = material.node_tree.links
    node = principled(material)
    node.inputs["Roughness"].default_value = .57
    if "Specular" in node.inputs:
        node.inputs["Specular"].default_value = .30
    if "Clearcoat" in node.inputs:
        node.inputs["Clearcoat"].default_value = .02
        node.inputs["Clearcoat Roughness"].default_value = .42

    albedo = nodes.new("ShaderNodeTexImage")
    albedo.name = "Sea lion original albedo"
    albedo.image = bpy.data.images.load(str(paths["albedo"]), check_existing=True)
    links.new(albedo.outputs["Color"], node.inputs["Base Color"])
    roughness = nodes.new("ShaderNodeTexImage")
    roughness.name = "Sea lion original wet roughness"
    roughness.image = bpy.data.images.load(str(paths["roughness"]), check_existing=True)
    roughness.image.colorspace_settings.name = "Non-Color"
    links.new(roughness.outputs["Color"], node.inputs["Roughness"])
    normal = nodes.new("ShaderNodeTexImage")
    normal.name = "Sea lion original skin normal"
    normal.image = bpy.data.images.load(str(paths["normal"]), check_existing=True)
    normal.image.colorspace_settings.name = "Non-Color"
    normal_map = nodes.new("ShaderNodeNormalMap")
    normal_map.inputs["Strength"].default_value = .15
    links.new(normal.outputs["Color"], normal_map.inputs["Color"])
    links.new(normal_map.outputs["Normal"], node.inputs["Normal"])
    return material


def relink_skin_material(material: bpy.types.Material, paths: Dict[str, Path]) -> None:
    for kind, node_name in (
        ("albedo", "Sea lion original albedo"),
        ("roughness", "Sea lion original wet roughness"),
        ("normal", "Sea lion original skin normal"),
    ):
        node = material.node_tree.nodes[node_name]
        old = node.image
        node.image = bpy.data.images.load(str(paths[kind]), check_existing=True)
        if kind != "albedo":
            node.image.colorspace_settings.name = "Non-Color"
        if old and old.users == 0:
            bpy.data.images.remove(old)


def ellipsoid(name: str, location, scale, material, segments=28, rotation=(0, 0, 0)) -> bpy.types.Object:
    bpy.ops.mesh.primitive_uv_sphere_add(segments=segments, ring_count=max(14, segments // 2), radius=1, location=location, rotation=rotation)
    obj = bpy.context.object
    obj.name = name
    obj.data.name = name
    obj.scale = scale
    select_only([obj])
    bpy.ops.object.transform_apply(location=False, rotation=True, scale=True)
    obj.data.materials.append(material)
    for polygon in obj.data.polygons:
        polygon.use_smooth = True
    return obj


def curve_mesh(
    name: str,
    points: Sequence[Sequence[float]],
    radius: float,
    material: bpy.types.Material | None,
    resolution=2,
) -> bpy.types.Object:
    curve = bpy.data.curves.new(name, "CURVE")
    curve.dimensions = "3D"
    curve.resolution_u = resolution
    curve.bevel_depth = radius
    curve.bevel_resolution = 2
    spline = curve.splines.new("BEZIER")
    spline.bezier_points.add(len(points) - 1)
    for point, coordinate in zip(spline.bezier_points, points):
        point.co = coordinate
        point.handle_left_type = "AUTO"
        point.handle_right_type = "AUTO"
    obj = bpy.data.objects.new(name, curve)
    bpy.context.collection.objects.link(obj)
    if material is not None:
        obj.data.materials.append(material)
    select_only([obj])
    bpy.context.view_layer.objects.active = obj
    bpy.ops.object.convert(target="MESH")
    return bpy.context.object


def tapered_whisker(name: str, points: Sequence[Sequence[float]], material: bpy.types.Material) -> bpy.types.Object:
    """Create a fine cubic, continuously tapered vibrissa with round sections."""
    controls = [Vector(point) for point in points]
    if len(controls) != 4:
        raise ValueError("tapered_whisker expects four cubic Bezier controls")
    radial = 5
    rings = 16
    vertices: List[Tuple[float, float, float]] = []
    for point_index in range(rings):
        t = point_index / (rings - 1)
        omt = 1 - t
        center = controls[0] * omt ** 3 + controls[1] * 3 * omt ** 2 * t + controls[2] * 3 * omt * t ** 2 + controls[3] * t ** 3
        tangent = (
            (controls[1] - controls[0]) * 3 * omt ** 2
            + (controls[2] - controls[1]) * 6 * omt * t
            + (controls[3] - controls[2]) * 3 * t ** 2
        ).normalized()
        reference = Vector((0, 0, 1)) if abs(tangent.z) < .86 else Vector((0, 1, 0))
        side_a = tangent.cross(reference).normalized()
        side_b = tangent.cross(side_a).normalized()
        radius = .00115 * (1 - t) ** 1.65 + .000055
        for side in range(radial):
            angle = math.tau * side / radial
            vertex = center + side_a * math.cos(angle) * radius + side_b * math.sin(angle) * radius
            vertices.append(tuple(vertex))
    faces: List[Tuple[int, ...]] = []
    for ring in range(rings - 1):
        for side in range(radial):
            nxt = (side + 1) % radial
            a = ring * radial
            b = (ring + 1) * radial
            faces.append((a + side, a + nxt, b + nxt, b + side))
    faces.append(tuple(reversed(range(radial))))
    final = (rings - 1) * radial
    faces.append(tuple(final + index for index in range(radial)))
    mesh = bpy.data.meshes.new(f"{name}Mesh")
    mesh.from_pydata(vertices, [], faces)
    mesh.update()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.collection.objects.link(obj)
    obj.data.materials.append(material)
    for polygon in obj.data.polygons:
        polygon.use_smooth = True
    return obj


def eyelid_rim(name: str, location: Sequence[float], normal: Vector, material: bpy.types.Material) -> bpy.types.Object:
    sign = 1 if normal.x >= 0 else -1
    x, y, z = location
    lid = curve_mesh(
        name,
        (
            (x + sign * .001, y - .012, z + .003),
            (x + sign * .005, y, z + .020),
            (x + sign * .001, y + .014, z + .002),
        ),
        .0022,
        material,
        3,
    )
    for polygon in lid.data.polygons:
        polygon.use_smooth = True
    return lid


def join_named(objects: Sequence[bpy.types.Object], name: str) -> bpy.types.Object:
    select_only(objects)
    bpy.context.view_layer.objects.active = objects[0]
    bpy.ops.object.join()
    result = bpy.context.object
    result.name = name
    result.data.name = name
    return result


def make_details(materials: Dict[str, bpy.types.Material]) -> Dict[str, bpy.types.Object]:
    details: Dict[str, bpy.types.Object] = {}
    eyes = []
    lids = []
    for side, sign in (("L", 1), ("R", -1)):
        location = (sign * .225, 1.377, 1.453)
        eyes.append(ellipsoid(f"Eye.{side}", location, (.023, .015, .020), materials["eye"], 40))
        lids.append(eyelid_rim(f"Eyelid.{side}", location, Vector((sign * .72, .68, .08)), materials["skin"]))
    details["eyes"] = join_named(eyes, "Eyes")
    details["eyelids"] = join_named(lids, "Eyelids")
    nose_base = ellipsoid("NoseBase", (0, 1.705, 1.333), (.076, .027, .043), materials["nose"], 40)
    nostrils = []
    for side, sign in (("L", 1), ("R", -1)):
        nostrils.append(ellipsoid(
            f"Nostril.{side}",
            (sign * .030, 1.735, 1.344),
            (.014, .0013, .006),
            materials["mouth"],
            24,
            (0, 0, math.radians(sign * 12)),
        ))
    details["nose"] = join_named([nose_base, *nostrils], "Nose")
    inner_ears = []
    for side, sign in (("L", 1), ("R", -1)):
        inner_ears.append(ellipsoid(f"InnerEar.{side}", (sign * .284, 1.071, 1.392), (.016, .024, .029), materials["inner_ear"], 24, (math.radians(-22), 0, 0)))
    details["inner_ears"] = join_named(inner_ears, "InnerEars")

    mouth = curve_mesh(
        "MouthLine",
        ((-.148, 1.610, 1.275), (-.080, 1.675, 1.268), (0, 1.688, 1.268),
         (.080, 1.675, 1.268), (.148, 1.610, 1.275)),
        .0034, materials["mouth"], 3,
    )
    philtrum = curve_mesh("Philtrum", ((0, 1.707, 1.325), (0, 1.695, 1.292), (0, 1.685, 1.270)), .0027, materials["mouth"], 3)
    details["mouth"] = join_named([mouth, philtrum], "Mouth")

    follicles = []
    whiskers = []
    for side, sign in (("L", 1), ("R", -1)):
        for row in range(5):
            vertical = row - 2
            z = 1.343 + vertical * .021
            start = (sign * (.105 + abs(vertical) * .004), 1.622, z)
            asymmetry = .008 * (1 if (row + (0 if side == "L" else 1)) % 2 else -1)
            mid_a = (sign * (.235 + row * .007), 1.678 + asymmetry, 1.347 + vertical * .030)
            mid_b = (sign * (.385 + row * .012), 1.660 + asymmetry * .5, 1.350 + vertical * .050 + asymmetry)
            end = (sign * (.535 + row * .016), 1.565 - row * .010 + asymmetry, 1.350 + vertical * .068 + asymmetry)
            whiskers.append(tapered_whisker(f"Whisker.{side}.{row}", (start, mid_a, mid_b, end), materials["whisker"]))
            follicles.append(ellipsoid(f"Follicle.{side}.{row}", start, (.0045, .003, .0045), materials["follicle"], 16))
    details["whiskers"] = join_named(whiskers, "Whiskers")
    details["follicles"] = join_named(follicles, "WhiskerFollicles")

    for obj in details.values():
        for polygon in obj.data.polygons:
            polygon.use_smooth = True
        inverse = obj.matrix_world.inverted()
        for vertex in obj.data.vertices:
            world = obj.matrix_world @ vertex.co
            world.y = compact_haul_out_y(world.y)
            vertex.co = inverse @ world
        obj.data.update()
    return details


def make_rig() -> bpy.types.Object:
    data = bpy.data.armatures.new("CaliforniaSeaLionRig")
    rig = bpy.data.objects.new("CaliforniaSeaLionRig", data)
    bpy.context.collection.objects.link(rig)
    select_only([rig])
    bpy.context.view_layer.objects.active = rig
    bpy.ops.object.mode_set(mode="EDIT")

    def bone(name, head, tail, parent=None, connected=False):
        item = data.edit_bones.new(name)
        item.head = (head[0], compact_haul_out_y(head[1]), head[2])
        item.tail = (tail[0], compact_haul_out_y(tail[1]), tail[2])
        if parent:
            item.parent = data.edit_bones[parent]
            item.use_connect = connected
        return item

    bone("Root", (0, 0, .10), (0, 0, .32))
    bone("Pelvis", (0, -.78, .52), (0, -.31, .61), "Root")
    bone("Spine", (0, -.31, .61), (0, .27, .72), "Pelvis", True)
    bone("Chest", (0, .27, .72), (0, .65, .92), "Spine", True)
    bone("NeckLower", (0, .65, .92), (0, .89, 1.08), "Chest", True)
    bone("NeckUpper", (0, .89, 1.08), (0, 1.16, 1.18), "NeckLower", True)
    bone("Head", (0, 1.16, 1.18), (0, 1.72, 1.13), "NeckUpper", True)
    bone("Jaw", (0, 1.47, 1.10), (0, 1.74, 1.05), "Head")
    bone("TailBase", (0, -1.02, .47), (0, -1.34, .36), "Pelvis")
    for side, sign in (("L", 1), ("R", -1)):
        bone(f"ForeFlipper.{side}", (sign * .28, .35, .54), (sign * .76, .47, .15), "Chest")
        bone(f"ForeTip.{side}", (sign * .76, .47, .15), (sign * 1.25, .60, .058), f"ForeFlipper.{side}", True)
        bone(f"HindFlipper.{side}", (sign * .10, -1.10, .28), (sign * .29, -1.68, .10), "TailBase")
        bone(f"HindTip.{side}", (sign * .29, -1.68, .10), (sign * .49, -2.20, .057), f"HindFlipper.{side}", True)
    bpy.ops.object.mode_set(mode="OBJECT")
    rig.show_in_front = True
    rig["asset_id"] = ASSET_ID
    rig["skeleton_contract"] = "pinniped-v1"
    return rig


def point_segment_distance(point: Vector, start: Vector, end: Vector) -> float:
    delta = end - start
    if delta.length_squared < 1e-12:
        return (point - start).length
    t = max(0, min(1, (point - start).dot(delta) / delta.length_squared))
    return (point - (start + delta * t)).length


def skin_object(obj: bpy.types.Object, rig: bpy.types.Object, rigid_bone: str | None = None) -> None:
    for group in list(obj.vertex_groups):
        obj.vertex_groups.remove(group)
    groups = {bone.name: obj.vertex_groups.new(name=bone.name) for bone in rig.data.bones}
    if rigid_bone:
        groups[rigid_bone].add([v.index for v in obj.data.vertices], 1, "REPLACE")
    else:
        axis = tuple(
            (name, compact_haul_out_y(y))
            for name, y in (
                ("TailBase", -1.18), ("Pelvis", -.72), ("Spine", -.15),
                ("Chest", .37), ("NeckLower", .70), ("NeckUpper", 1.00),
                ("Head", 1.30),
            )
        )

        def smoothstep(value: float) -> float:
            value = max(0.0, min(1.0, value))
            return value * value * (3 - 2 * value)

        def assign(vertex_index: int, assignments: Dict[str, float]) -> None:
            total = sum(max(weight, 0) for weight in assignments.values())
            for name, weight in assignments.items():
                if weight > .0001:
                    groups[name].add([vertex_index], weight / total, "REPLACE")

        for vertex in obj.data.vertices:
            p = vertex.co
            lateral = abs(p.x)
            axial_weights: Dict[str, float] = {}
            if p.y <= axis[0][1]:
                axial_weights[axis[0][0]] = 1
            elif p.y >= axis[-1][1]:
                axial_weights[axis[-1][0]] = 1
            else:
                for (left_name, left_y), (right_name, right_y) in zip(axis, axis[1:]):
                    if left_y <= p.y <= right_y:
                        blend = smoothstep((p.y - left_y) / (right_y - left_y))
                        axial_weights = {left_name: 1 - blend, right_name: blend}
                        break

            # Continuous shoulder-to-web field.  The axial weights fade out
            # over a broad girdle instead of switching at a geometric test,
            # keeping every edge on both sides of the root within the same
            # four-influence envelope.
            side = "L" if p.x >= 0 else "R"
            fore_lateral = smoothstep((lateral - .17) / .34)
            fore_lower = smoothstep((.83 - p.z) / .28)
            fore_front = smoothstep((p.y + .08) / .18)
            # The fan sweeps forward to y≈.62.  Saturate the appendage field
            # before that distal edge so it transforms as one hydrofoil;
            # fading back into Chest at the tip was the source of the former
            # foldover and triangle inversions in Swim/Dive.
            fore_back = smoothstep((.82 - p.y) / .14)
            fore_gate = fore_lateral * fore_lower * min(fore_front, fore_back)
            assignments = {
                name: weight * (1 - fore_gate)
                for name, weight in axial_weights.items()
            }
            # The approved broad fan behaves as a single hydrofoil.  Keeping
            # the web on ForeFlipper avoids candy-wrapper collapse from linear
            # blending between differently oriented root and tip bones.  The
            # stable ForeTip bones and animation channels remain in the public
            # pinniped-v1 interface for runtime compatibility.
            assignments[f"ForeFlipper.{side}"] = assignments.get(f"ForeFlipper.{side}", 0) + fore_gate

            # The paired rear webs share TailBase smoothly through the midline;
            # bilateral hind influences only take over once lateral separation
            # is established, eliminating the former center-seam tearing.
            hind_rear = smoothstep((-p.y - .82) / .30)
            hind_lateral = smoothstep((lateral - .008) / .13)
            hind_gate = hind_rear * hind_lateral
            if hind_gate > 0:
                assignments = {
                    name: weight * (1 - hind_gate)
                    for name, weight in assignments.items()
                }
                hind_tip = smoothstep((-p.y - 1.39) / .46)
                assignments[f"HindFlipper.{side}"] = assignments.get(f"HindFlipper.{side}", 0) + hind_gate * (1 - hind_tip)
                assignments[f"HindTip.{side}"] = assignments.get(f"HindTip.{side}", 0) + hind_gate * hind_tip
            assign(vertex.index, assignments)
    modifier = obj.modifiers.new("CaliforniaSeaLionRig", "ARMATURE")
    modifier.object = rig
    obj.parent = rig
    obj.matrix_parent_inverse = rig.matrix_world.inverted()


def reset_pose(rig: bpy.types.Object) -> None:
    for bone in rig.pose.bones:
        bone.rotation_mode = "XYZ"
        bone.location = (0, 0, 0)
        bone.rotation_euler = (0, 0, 0)
        bone.scale = (1, 1, 1)


def action_begin(rig: bpy.types.Object, name: str) -> bpy.types.Action:
    reset_pose(rig)
    action = bpy.data.actions.new(name)
    action.use_fake_user = True
    rig.animation_data_create()
    rig.animation_data.action = action
    return action


def key(rig, bone_name, frame, rotation=None, location=None, scale=None, group=""):
    bone = rig.pose.bones[bone_name]
    bone.rotation_mode = "XYZ"
    if rotation is not None:
        bone.rotation_euler = rotation
        bone.keyframe_insert("rotation_euler", frame=frame, group=group)
    if location is not None:
        bone.location = location
        bone.keyframe_insert("location", frame=frame, group=group)
    if scale is not None:
        bone.scale = scale
        bone.keyframe_insert("scale", frame=frame, group=group)


def finish_action(action: bpy.types.Action, interpolation="BEZIER") -> bpy.types.Action:
    for fcurve in action.fcurves:
        for point in fcurve.keyframe_points:
            point.interpolation = interpolation
    return action


def make_idle(rig) -> bpy.types.Action:
    name = "SeaLionIdle"
    action = action_begin(rig, name)
    for frame, breath, look in ((1, 0, 0), (30, .013, -.08), (60, 0, .05), (90, .011, .11), (120, 0, 0)):
        key(rig, "Root", frame, location=(0, 0, 0), group=name)
        key(rig, "Chest", frame, scale=(1 + breath * .4, 1 + breath * .5, 1 + breath), rotation=(0, 0, look * .13), group=name)
        key(rig, "NeckLower", frame, rotation=(-look * .08, 0, look * .32), group=name)
        key(rig, "NeckUpper", frame, rotation=(-look * .10, 0, look * .52), group=name)
        key(rig, "Head", frame, rotation=(look * .08, 0, look), group=name)
        for side, sign in (("L", 1), ("R", -1)):
            key(rig, f"ForeFlipper.{side}", frame, rotation=(0, 0, sign * breath * 1.5), group=name)
            key(rig, f"HindFlipper.{side}", frame, rotation=(0, 0, 0), group=name)
            key(rig, f"HindTip.{side}", frame, rotation=(0, 0, 0), group=name)
    return finish_action(action)


def make_swim(rig) -> bpy.types.Action:
    name = "SeaLionSwim"
    action = action_begin(rig, name)
    for frame, phase in ((1, 0), (10, math.pi / 2), (19, math.pi), (28, math.pi * 1.5), (37, math.tau)):
        stroke = math.sin(phase)
        recovery = math.cos(phase)
        key(rig, "Root", frame, location=(0, 0, math.sin(phase * 2) * .018), rotation=(math.radians(-3) + stroke * math.radians(2), 0, stroke * math.radians(2.5)), group=name)
        key(rig, "Spine", frame, rotation=(stroke * math.radians(3), 0, -stroke * math.radians(4)), group=name)
        key(rig, "Chest", frame, rotation=(-stroke * math.radians(2), 0, stroke * math.radians(3)), group=name)
        key(rig, "NeckLower", frame, rotation=(-stroke * math.radians(2), 0, -stroke * math.radians(2)), group=name)
        for side, sign in (("L", 1), ("R", -1)):
            # Strong foreflipper power stroke beneath the chest, followed by a
            # narrower recovery close to the body.
            # Keep the broad fan presented to the water throughout the cycle.
            # A former negative local-X twist turned the thin hydrofoil edge-on
            # and made the imported silhouette read as a severed paddle.
            fore_pitch = math.radians(7) + recovery * math.radians(5)
            key(rig, f"ForeFlipper.{side}", frame, rotation=(fore_pitch, sign * (math.radians(-3) + stroke * math.radians(7)), sign * (math.radians(2) + stroke * math.radians(12))), group=name)
            key(rig, f"ForeTip.{side}", frame, rotation=(-recovery * math.radians(6), sign * stroke * math.radians(4), sign * stroke * math.radians(4)), group=name)
            key(rig, f"HindFlipper.{side}", frame, rotation=(stroke * math.radians(2), 0, sign * stroke * math.radians(4)), group=name)
            key(rig, f"HindTip.{side}", frame, rotation=(-stroke * math.radians(2), 0, sign * stroke * math.radians(3)), group=name)
    return finish_action(action, "BEZIER")


def make_surface(rig) -> bpy.types.Action:
    name = "SeaLionSurface"
    action = action_begin(rig, name)
    for frame, amount in ((1, 0), (24, .45), (48, 1), (78, .72), (108, 0)):
        key(rig, "Root", frame, location=(0, 0, amount * .10), rotation=(amount * math.radians(4), 0, 0), group=name)
        key(rig, "Chest", frame, rotation=(amount * math.radians(2), 0, 0), group=name)
        key(rig, "NeckLower", frame, rotation=(amount * math.radians(5), 0, 0), group=name)
        key(rig, "NeckUpper", frame, rotation=(amount * math.radians(6), 0, 0), group=name)
        key(rig, "Head", frame, rotation=(amount * math.radians(3), 0, 0), group=name)
        for side, sign in (("L", 1), ("R", -1)):
            key(rig, f"ForeFlipper.{side}", frame, rotation=(amount * math.radians(6), 0, sign * amount * math.radians(8)), group=name)
    return finish_action(action)


def make_dive(rig) -> bpy.types.Action:
    name = "SeaLionDive"
    action = action_begin(rig, name)
    for frame, amount in ((1, 0), (22, .35), (46, 1), (72, .75), (96, 0)):
        key(rig, "Root", frame, location=(0, amount * .04, -amount * .04), rotation=(-amount * math.radians(5), 0, 0), group=name)
        key(rig, "Chest", frame, rotation=(-amount * math.radians(2), 0, 0), group=name)
        key(rig, "NeckLower", frame, rotation=(-amount * math.radians(5), 0, 0), group=name)
        key(rig, "NeckUpper", frame, rotation=(-amount * math.radians(6), 0, 0), group=name)
        key(rig, "Head", frame, rotation=(-amount * math.radians(3), 0, 0), group=name)
        for side, sign in (("L", 1), ("R", -1)):
            key(rig, f"ForeFlipper.{side}", frame, rotation=(amount * math.radians(3), sign * amount * math.radians(3), sign * amount * math.radians(8)), group=name)
            key(rig, f"ForeTip.{side}", frame, rotation=(-amount * math.radians(5), 0, sign * amount * math.radians(3)), group=name)
    return finish_action(action)


def install_tracks(rig, actions: Sequence[bpy.types.Action]) -> None:
    rig.animation_data_create()
    rig.animation_data.action = None
    for track in list(rig.animation_data.nla_tracks):
        rig.animation_data.nla_tracks.remove(track)
    for action in actions:
        track = rig.animation_data.nla_tracks.new()
        track.name = action.name
        strip = track.strips.new(action.name, int(action.frame_range[0]), action)
        strip.action_frame_start = action.frame_range[0]
        strip.action_frame_end = action.frame_range[1]
    reset_pose(rig)


def limit_influences(obj: bpy.types.Object, maximum=4) -> None:
    for vertex in obj.data.vertices:
        assignments = sorted(((g.group, g.weight) for g in vertex.groups if g.weight > 1e-8), key=lambda item: item[1], reverse=True)
        if not assignments:
            continue
        for index, _ in assignments[maximum:]:
            obj.vertex_groups[index].remove([vertex.index])
        kept = assignments[:maximum]
        total = sum(weight for _, weight in kept)
        for index, weight in kept:
            obj.vertex_groups[index].add([vertex.index], weight / total, "REPLACE")


def triangulate(meshes: Sequence[bpy.types.Object]) -> None:
    for obj in meshes:
        mesh = bmesh.new()
        mesh.from_mesh(obj.data)
        bmesh.ops.triangulate(mesh, faces=list(mesh.faces))
        mesh.to_mesh(obj.data)
        mesh.free()
        obj.data.update()


def duplicate_lod(meshes, rig, ratio=.32):
    select_only([*meshes, rig])
    bpy.ops.object.duplicate()
    selected = list(bpy.context.selected_objects)
    lod_rig = next(obj for obj in selected if obj.type == "ARMATURE")
    lod_rig.name = "CaliforniaSeaLionRig.LOD2"
    lod_meshes = [obj for obj in selected if obj.type == "MESH"]
    for obj in lod_meshes:
        obj.name = f"{obj.name}.LOD2"
        obj.parent = lod_rig
        for modifier in list(obj.modifiers):
            if modifier.type == "ARMATURE":
                obj.modifiers.remove(modifier)
        if len(obj.data.polygons) > 900:
            decimate = obj.modifiers.new("Silhouette-aware LOD2 decimation", "DECIMATE")
            decimate.decimate_type = "COLLAPSE"
            decimate.ratio = ratio
            decimate.use_collapse_triangulate = True
            decimate.use_symmetry = True
            apply_modifier(obj, decimate.name)
            limit_influences(obj)
        armature = obj.modifiers.new("CaliforniaSeaLionRig", "ARMATURE")
        armature.object = lod_rig
    return lod_meshes, lod_rig


def gltf_export(path: Path, objects: Sequence[bpy.types.Object]) -> None:
    select_only(objects)
    kwargs = dict(
        filepath=str(path), export_format="GLB", use_selection=True,
        export_yup=True, export_apply=False, export_texcoords=True,
        export_normals=True, export_tangents=True, export_materials="EXPORT",
        export_colors=False, export_cameras=False, export_lights=False,
        export_skins=True, export_def_bones=True, export_animations=True,
        export_frame_range=True, export_force_sampling=False,
        export_nla_strips=True, export_optimize_animation_size=True,
        export_draco_mesh_compression_enable=True,
        export_draco_mesh_compression_level=6,
        export_draco_position_quantization=14,
        export_draco_normal_quantization=10,
        export_draco_texcoord_quantization=12,
        export_draco_generic_quantization=12,
        export_extras=True,
    )
    try:
        bpy.ops.export_scene.gltf(**kwargs)
    except TypeError:
        for optional in ("export_force_sampling", "export_optimize_animation_size", "export_nla_strips"):
            kwargs.pop(optional, None)
        bpy.ops.export_scene.gltf(**kwargs)


def aim(obj, target: Sequence[float]) -> None:
    obj.rotation_euler = (Vector(target) - obj.location).to_track_quat("-Z", "Y").to_euler()


def preview_material(name, color, roughness, alpha=1):
    material = simple_material(name, (*color, alpha), roughness)
    if alpha < 1:
        material.blend_method = "BLEND"
        material.use_nodes = True
        principled(material).inputs["Alpha"].default_value = alpha
        material.show_transparent_back = False
    return material


def add_preview_environment() -> List[bpy.types.Object]:
    helpers: List[bpy.types.Object] = []
    bpy.ops.mesh.primitive_plane_add(size=12, location=(0, 0, .088))
    ground = bpy.context.object
    ground.name = "QA.GroundContactPlane"
    ground.data.materials.append(preview_material("QA dark stone", (.025, .035, .038), .72))
    helpers.append(ground)
    for name, location, energy, size, color in (
        ("QA.Key", (-3.5, 4.2, 5.0), 350, 3.2, (1.0, .80, .66)),
        ("QA.Fill", (3.8, 1.2, 3.2), 210, 3.0, (.54, .72, 1.0)),
        ("QA.Rim", (-2.0, -3.5, 3.8), 370, 2.6, (.48, .80, 1.0)),
    ):
        bpy.ops.object.light_add(type="AREA", location=location)
        light = bpy.context.object
        light.name = name
        light.data.energy = energy
        light.data.size = size
        light.data.color = color
        aim(light, (0, 0, .75))
        helpers.append(light)
    return helpers


def render_previews(rig, actions: Sequence[bpy.types.Action], directory: Path) -> Dict[str, str]:
    directory.mkdir(parents=True, exist_ok=True)
    scene = bpy.context.scene
    scene.render.engine = "BLENDER_EEVEE"
    scene.eevee.taa_render_samples = 64
    scene.eevee.use_gtao = True
    scene.eevee.gtao_distance = 3
    scene.eevee.gtao_factor = 1.3
    scene.render.resolution_x = 1200
    scene.render.resolution_y = 900
    scene.render.resolution_percentage = 100
    scene.render.image_settings.file_format = "PNG"
    scene.world.use_nodes = True
    scene.world.node_tree.nodes["Background"].inputs["Color"].default_value = (.008, .016, .023, 1)
    scene.world.node_tree.nodes["Background"].inputs["Strength"].default_value = .24
    scene.view_settings.look = "Medium High Contrast"
    scene.view_settings.exposure = -.08
    helpers = add_preview_environment()
    bpy.ops.object.camera_add(location=(3.75, 4.35, 2.35))
    camera = bpy.context.object
    camera.name = "QA.FixedCamera"
    camera.data.lens = 62
    aim(camera, (0, .02, .75))
    scene.camera = camera
    helpers.append(camera)

    bpy.ops.mesh.primitive_cube_add(size=1, location=(0, 0, .60))
    surface_water = bpy.context.object
    surface_water.name = "QA.SurfaceWater"
    surface_water.scale = (2.8, 3.4, .012)
    surface_water.data.materials.append(preview_material("QA surface water", (.015, .30, .42), .20, .30))
    surface_water.hide_render = True
    helpers.append(surface_water)

    frames = {"SeaLionIdle": 30, "SeaLionSwim": 10, "SeaLionSurface": 48, "SeaLionDive": 46}
    outputs: Dict[str, str] = {}
    rig.animation_data_create()
    for action in actions:
        rig.animation_data.action = action
        scene.frame_set(frames[action.name])
        surface_water.hide_render = action.name != "SeaLionSurface"
        path = directory / f"{ASSET_ID}-{action.name}.png"
        scene.render.filepath = str(path)
        bpy.ops.render.render(write_still=True)
        outputs[action.name] = str(path)

    # Face close-up checks eye/nose/pinna embedding and whisker roots.
    rig.animation_data.action = next(a for a in actions if a.name == "SeaLionIdle")
    surface_water.hide_render = True
    scene.frame_set(30)
    camera.location = (1.10, 2.34, 1.53)
    camera.data.lens = 74
    aim(camera, (0, 1.47, 1.18))
    scene.render.resolution_x = 1100
    scene.render.resolution_y = 900
    face = directory / f"{ASSET_ID}-face-closeup.png"
    scene.render.filepath = str(face)
    bpy.ops.render.render(write_still=True)
    outputs["FaceCloseup"] = str(face)

    # A close side view makes root continuity and blade taper unambiguous.
    camera.location = (1.52, .12, 2.28)
    camera.data.lens = 68
    aim(camera, (.62, -.05, .47))
    flipper = directory / f"{ASSET_ID}-foreflipper-closeup.png"
    scene.render.filepath = str(flipper)
    bpy.ops.render.render(write_still=True)
    outputs["ForeflipperCloseup"] = str(flipper)

    # The rear review is deliberately more dorsal so both bilateral hind
    # flippers and the tapered webbed digit channels remain readable.
    camera.location = (1.40, -2.15, 1.60)
    camera.data.lens = 74
    aim(camera, (0, -1.48, .30))
    hind_flipper = directory / f"{ASSET_ID}-hindflipper-closeup.png"
    scene.render.filepath = str(hind_flipper)
    bpy.ops.render.render(write_still=True)
    outputs["HindflipperCloseup"] = str(hind_flipper)

    camera.location = (2.65, -3.15, 1.38)
    camera.data.lens = 64
    aim(camera, (0, -.63, .50))
    rear = directory / f"{ASSET_ID}-rear-three-quarter.png"
    scene.render.filepath = str(rear)
    bpy.ops.render.render(write_still=True)
    outputs["RearThreeQuarter"] = str(rear)

    # Review guide: cyan waterline at the shoulder and amber contact markers at
    # the planted belly/flipper plane. These helpers never enter the GLBs.
    bpy.ops.mesh.primitive_cube_add(size=1, location=(0, 0, .68))
    waterline = bpy.context.object
    waterline.name = "QA.WaterlineGuide"
    waterline.scale = (2.2, 2.4, .012)
    waterline.data.materials.append(preview_material("QA waterline cyan", (.01, .58, .82), .18, .24))
    helpers.append(waterline)
    markers = []
    for x, y in ((-.66, -.07), (.66, -.07), (-.20, -1.28), (.20, -1.28), (0, -.18)):
        bpy.ops.mesh.primitive_uv_sphere_add(segments=20, ring_count=10, radius=.032, location=(x, y, .10))
        marker = bpy.context.object
        marker.name = "QA.ContactMarker"
        marker.data.materials.append(preview_material("QA contact amber", (1.0, .36, .025), .32))
        markers.append(marker)
    helpers.extend(markers)
    camera.location = (3.75, 4.35, 2.35)
    camera.data.lens = 62
    aim(camera, (0, .02, .72))
    scene.render.resolution_x = 1200
    guide = directory / f"{ASSET_ID}-waterline-ground-contact.png"
    scene.render.filepath = str(guide)
    bpy.ops.render.render(write_still=True)
    outputs["WaterlineGroundContact"] = str(guide)

    rig.animation_data.action = None
    scene.frame_set(1)
    for obj in helpers:
        if obj.name in bpy.data.objects:
            bpy.data.objects.remove(obj, do_unlink=True)
    return outputs


def glb_json(path: Path) -> Dict:
    with path.open("rb") as handle:
        magic, version, length = struct.unpack("<4sII", handle.read(12))
        if magic != b"glTF" or version != 2:
            raise RuntimeError(f"{path} is not glTF 2.0")
        while handle.tell() < length:
            chunk_length, chunk_type = struct.unpack("<II", handle.read(8))
            data = handle.read(chunk_length)
            if chunk_type == 0x4E4F534A:
                return json.loads(data.decode("utf-8"))
    raise RuntimeError(f"{path} has no JSON chunk")


def verify_glb(path: Path) -> Dict[str, object]:
    data = glb_json(path)
    clips = [animation.get("name") for animation in data.get("animations", [])]
    missing = [name for name in CLIP_NAMES if name not in clips]
    if missing:
        raise RuntimeError(f"{path.name} missing clips {missing}; found {clips}")
    if not data.get("skins"):
        raise RuntimeError(f"{path.name} has no skin")
    primitives = [primitive for mesh in data.get("meshes", []) for primitive in mesh.get("primitives", [])]
    if not any("JOINTS_0" in primitive.get("attributes", {}) and "WEIGHTS_0" in primitive.get("attributes", {}) for primitive in primitives):
        raise RuntimeError(f"{path.name} has no skinned primitive")
    if not any(material.get("normalTexture") for material in data.get("materials", [])):
        raise RuntimeError(f"{path.name} has no normal-mapped material")
    triangles = sum(data["accessors"][primitive["indices"]]["count"] // 3 for primitive in primitives)
    vertices = sum(data["accessors"][primitive["attributes"]["POSITION"]]["count"] for primitive in primitives)
    return {
        "animations": clips,
        "skins": len(data.get("skins", [])),
        "bones": max(len(skin.get("joints", [])) for skin in data.get("skins", [])),
        # Three GLTFLoader instantiates one runtime mesh per primitive. A
        # multi-material source mesh therefore counts more than once here.
        "meshes": len(primitives),
        "materials": len(data.get("materials", [])),
        "embeddedImages": len(data.get("images", [])),
        "triangles": triangles,
        "vertices": vertices,
    }


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def object_bounds(obj: bpy.types.Object) -> Tuple[Vector, Vector]:
    corners = [obj.matrix_world @ Vector(corner) for corner in obj.bound_box]
    return (
        Vector((min(p.x for p in corners), min(p.y for p in corners), min(p.z for p in corners))),
        Vector((max(p.x for p in corners), max(p.y for p in corners), max(p.z for p in corners))),
    )


def main() -> None:
    args = parse_args()
    args.output = args.output.resolve()
    args.source = args.source.resolve()
    if args.preview:
        args.preview = args.preview.resolve()
    args.output.mkdir(parents=True, exist_ok=True)
    args.source.mkdir(parents=True, exist_ok=True)
    purge()
    scene = bpy.context.scene
    scene.render.fps = 30
    scene.unit_settings.system = "METRIC"
    scene.unit_settings.scale_length = 1

    source_maps = write_source_maps(args.source, args.texture_size)
    runtime_maps = make_runtime_maps(source_maps)
    materials = {
        "skin": make_skin_material(runtime_maps),
        "eye": simple_material("SeaLionEyes", (.014, .007, .004, 1), .30),
        "nose": simple_material("SeaLionMoistNose", (.020, .010, .007, 1), .48),
        "inner_ear": simple_material("SeaLionInnerEar", (.055, .026, .019, 1), .34),
        "mouth": simple_material("SeaLionMouth", (.028, .010, .009, 1), .38),
        "whisker": simple_material("SeaLionWhiskers", (.48, .42, .34, 1), .62),
        "follicle": simple_material("SeaLionWhiskerFollicles", (.026, .012, .008, 1), .42),
    }
    for name, strength in (("nose", .24), ("mouth", .20)):
        node = principled(materials[name])
        if "Specular" in node.inputs:
            node.inputs["Specular"].default_value = strength
    body = create_continuous_skin(args.voxel_size)
    smart_uv(body)
    body.data.materials.append(materials["skin"])
    details = make_details(materials)
    for detail in details.values():
        smart_uv(detail)
    rig = make_rig()
    skin_object(body, rig)
    for name in ("eyes", "eyelids", "nose", "inner_ears", "mouth", "whiskers", "follicles"):
        skin_object(details[name], rig, "Head")
    # Sculpting coordinates favor comfortable numerical precision. A single
    # authored rig transform brings the delivered adult male to plausible
    # real-world proportions while preserving every bind matrix and clip.
    rig.scale = (.64, .88, .98)
    meshes = [body, *details.values()]
    actions = [make_idle(rig), make_swim(rig), make_surface(rig), make_dive(rig)]
    install_tracks(rig, actions)
    triangulate(meshes)

    previews = render_previews(rig, actions, args.preview) if args.preview else {}
    install_tracks(rig, actions)
    lod2_meshes, lod2_rig = duplicate_lod(meshes, rig, .32)
    triangulate(lod2_meshes)

    lod0_path = args.output / f"{ASSET_ID}-lod0.glb"
    lod2_path = args.output / f"{ASSET_ID}-lod2.glb"
    gltf_export(lod0_path, [*meshes, rig])
    gltf_export(lod2_path, [*lod2_meshes, lod2_rig])
    lod0 = verify_glb(lod0_path)
    lod2 = verify_glb(lod2_path)
    low, high = object_bounds(body)
    dimensions = high - low

    manifest = {
        "schemaVersion": 1,
        "id": ASSET_ID,
        "displayName": "California sea lion",
        "species": "Zalophus californianus",
        "license": "Original-Project-Asset",
        "generator": "tools/animal-pipeline/build_sea_lion.py",
        "provenance": {
            "geometry": "Original repository-authored axial and rounded webbed-appendage lofts, fused into one watertight skin; no third-party geometry.",
            "textures": "Original deterministic NumPy-generated wet-skin PBR maps; no third-party pixels.",
            "rigging": "Original pinniped skeleton, weights and animation curves authored by this pipeline.",
            "referencePolicy": "Wildlife photographs and zoo species facts used only for anatomical proportion and locomotion study.",
            "visualReferences": [
                "https://www.fisheries.noaa.gov/species/california-sea-lion",
                "https://animals.sandiegozoo.org/animals/sea-lion",
            ],
        },
        "coordinateSystem": {"unit": "meter", "up": "+Y", "forward": "-Z", "origin": "ground-contact plane"},
        "dimensionsMeters": {"width": round(dimensions.x, 3), "length": round(dimensions.y, 3), "height": round(dimensions.z, 3)},
        "skeleton": {"name": "CaliforniaSeaLionRig", "bones": [bone.name for bone in rig.data.bones], "maxInfluences": 4},
        "clips": [{"name": name} for name in CLIP_NAMES],
        "materials": [material.name for material in materials.values()],
        "maps": {
            kind: {
                "kind": kind,
                "sourceFile": str(path.relative_to(Path.cwd())),
                "embeddedImageName": f"{ASSET_ID}-{kind}",
                "width": args.texture_size,
                "height": args.texture_size,
                "bytes": path.stat().st_size,
                "sha256": sha256(path),
                "runtimeMimeType": "image/png" if kind == "roughness" else "image/jpeg",
            }
            for kind, path in source_maps.items()
        },
        "lod0": {"file": lod0_path.name, "bytes": lod0_path.stat().st_size, "sha256": sha256(lod0_path), **lod0},
        "lod2": {"file": lod2_path.name, "bytes": lod2_path.stat().st_size, "sha256": sha256(lod2_path), **lod2},
        "previews": previews,
    }
    asset_manifest = args.source / f"{ASSET_ID}.asset.json"
    asset_manifest.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    metrics_path = Path(__file__).resolve().parent / f"{ASSET_ID}-metrics.json"
    metrics_path.write_text(json.dumps({
        "speciesId": ASSET_ID,
        "dimensionsMeters": manifest["dimensionsMeters"],
        "skeleton": manifest["skeleton"],
        "clips": list(CLIP_NAMES),
        "lod0": manifest["lod0"],
        "lod2": manifest["lod2"],
        "maps": manifest["maps"],
        "previews": previews,
    }, indent=2, sort_keys=True) + "\n")
    provenance_path = args.source / f"{ASSET_ID}.provenance.json"
    provenance_path.write_text(json.dumps({
        "speciesId": ASSET_ID,
        "license": "Original-Project-Asset",
        "source": "tools/animal-pipeline/build_sea_lion.py",
        "generatedSourceBlend": f"tools/animal-pipeline/source/{ASSET_ID}-source.blend",
        "thirdPartyAssets": [],
        "visualReferences": manifest["provenance"]["visualReferences"],
        "referenceUse": "Anatomy and locomotion study only; no geometry or pixels copied.",
    }, indent=2, sort_keys=True) + "\n")

    if args.keep_blend:
        relink_skin_material(materials["skin"], source_maps)
        bpy.context.preferences.filepaths.save_version = 0
        bpy.ops.wm.save_as_mainfile(filepath=str(args.source / f"{ASSET_ID}-source.blend"))
    print(json.dumps(manifest, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
