export type EducationContext =
  | "central-park"
  | "central-park-landmarks"
  | "the-lake"
  | "subway"
  | "subway-train"
  | "bronx-zoo"
  | "zoo-polar-bear"
  | "zoo-sloth"
  | "zoo-sea-lion"
  | "zoo-spider-monkey"
  | "zoo-birds"
  | "zoo-zebra"
  | "zoo-red-panda"
  | "zoo-tortoise"
  | "zoo-flamingo"
  | "zoo-bison"
  | "city"
  | "museum"
  | "homecoming";

export type EducationFact = {
  id: string;
  contexts: readonly EducationContext[];
  title: string;
  teaser: string;
  detail: string;
  wikiTitle: string;
};

const fact = (
  id: string,
  contexts: readonly EducationContext[],
  title: string,
  teaser: string,
  detail: string,
  wikiTitle: string,
): EducationFact => ({ id, contexts, title, teaser, detail, wikiTitle });

/**
 * Every entry deliberately resolves to an English Wikipedia article. Facts are
 * grouped by the place in which the player encounters them so the education
 * layer follows the trip instead of behaving like a detached trivia screen.
 */
export const EDUCATION_FACTS: readonly EducationFact[] = [
  fact(
    "park-size",
    ["central-park", "homecoming"],
    "A very large backyard",
    "Central Park covers 843 acres in the middle of Manhattan.",
    "The park stretches about 2.5 miles north to south and roughly half a mile east to west. Its 843 acres contain woodlands, lawns, water, roads, paths, and more than twenty playgrounds.",
    "Central_Park",
  ),
  fact(
    "park-greensward",
    ["central-park", "homecoming"],
    "The Greensward Plan",
    "Frederick Law Olmsted and Calvert Vaux won the 1858 competition to design Central Park.",
    "Their Greensward Plan used curving pedestrian routes, separated circulation, and carefully composed scenery to make the park feel removed from the street grid. Much of the landscape that looks natural was deliberately engineered.",
    "Greensward_Plan",
  ),
  fact(
    "park-transverses",
    ["central-park", "homecoming"],
    "Traffic hidden in the landscape",
    "Four sunken transverse roads carry crosstown traffic through Central Park.",
    "Olmsted and Vaux placed the park's transverse roads below many pedestrian paths. This separation let carts—and later cars—cross Manhattan while preserving long, uninterrupted park views.",
    "Central_Park",
  ),
  fact(
    "park-ramble",
    ["central-park"],
    "The Ramble is designed wilderness",
    "The Ramble is a 36-acre woodland created to feel like an untamed walk.",
    "Its winding paths, rocky outcrops, planted woodland, and deliberately irregular shorelines were part of the original park design. The maze-like route was intended for strolling and discovery rather than direct travel.",
    "The_Ramble_and_Lake",
  ),
  fact(
    "park-bedrock",
    ["central-park", "homecoming"],
    "Ancient rock underfoot",
    "Many Central Park outcrops are Manhattan schist, a metamorphic rock shaped deep underground.",
    "Manhattan schist is strong enough to support many of the city's tall buildings where it lies close to the surface. In the park, exposed ridges let visitors see bedrock that is usually hidden below streets and towers.",
    "Manhattan_schist",
  ),
  fact(
    "park-glaciers",
    ["central-park", "homecoming"],
    "Glaciers left clues",
    "Grooves and scattered boulders in Central Park record the last Ice Age.",
    "Moving ice polished and scratched exposed bedrock and carried large stones away from their original formations. Such transported boulders are called glacial erratics.",
    "Glacial_erratic",
  ),
  fact(
    "park-seneca-village",
    ["central-park", "homecoming"],
    "A community before the park",
    "Seneca Village was a predominantly Black community on land that later became Central Park.",
    "Founded in 1825, Seneca Village included homes, churches, and a school near today's West 82nd to 89th Streets. New York acquired the land through eminent domain in 1857 and displaced its residents to build the park.",
    "Seneca_Village",
  ),
  fact(
    "park-birds",
    ["central-park", "homecoming"],
    "A stopover in the sky",
    "Central Park is an important resting and feeding place for migrating birds.",
    "The park's woodlands and water sit along the Atlantic Flyway, a major north-south migration route. Concentrated green habitat amid dense development makes the park especially valuable to tired migrants.",
    "Central_Park",
  ),
  fact(
    "park-landmark-status",
    ["central-park", "homecoming"],
    "A protected landscape",
    "Central Park became a National Historic Landmark in 1963.",
    "The federal designation recognizes the park's national importance in landscape architecture and urban planning. New York City later designated it a scenic landmark as well.",
    "Central_Park",
  ),
  fact(
    "park-squirrel",
    ["central-park", "homecoming"],
    "The park's busy seed planters",
    "Eastern gray squirrels often forget some buried food, helping trees spread.",
    "Gray squirrels scatter-hoard nuts in many small caches instead of one pantry. Their strong spatial memory recovers many caches, but forgotten seeds can germinate into new plants.",
    "Eastern_gray_squirrel",
  ),
  fact(
    "park-mallard",
    ["central-park", "the-lake", "homecoming"],
    "A duck found across the world",
    "The mallard is native across much of the Northern Hemisphere and has been introduced elsewhere.",
    "Mallards are dabbling ducks: they feed near the surface by tipping forward rather than diving deeply. Domestic duck breeds descend mainly from mallards, with a few notable exceptions.",
    "Mallard",
  ),
  fact(
    "lake-made",
    ["the-lake"],
    "A lake built for the park",
    "Central Park's Lake is an artificial water body created as part of the original design.",
    "The designers transformed swampy ground and a smaller natural watercourse into a broad scenic lake. Its irregular shoreline was shaped to create changing views as visitors moved around it.",
    "The_Ramble_and_Lake",
  ),
  fact(
    "lake-area",
    ["the-lake"],
    "Twenty acres of water",
    "The Lake occupies about 20 acres south of the Ramble.",
    "The water separates the Ramble from Bethesda Terrace and the lawns to the south. It has supported boating, skating, wildlife habitat, and some of Central Park's best-known views.",
    "The_Ramble_and_Lake",
  ),
  fact(
    "lake-boating",
    ["the-lake"],
    "Boats belong to the original experience",
    "Rowing on the Lake became popular soon after Central Park opened.",
    "The Lake was designed for recreation as well as scenery. Boat landings and boathouses changed over time, but rowing has remained one of the ways visitors experience the deliberately varied shoreline.",
    "Loeb_Boathouse",
  ),
  fact(
    "bow-bridge",
    ["the-lake", "central-park-landmarks"],
    "A cast-iron ribbon",
    "Bow Bridge was completed in 1862 and spans the narrow waist of the Lake.",
    "Calvert Vaux and Jacob Wrey Mould designed the graceful cast-iron bridge. Its low arch connects Cherry Hill with the Ramble and frames long views across the water.",
    "Bow_Bridge_(Central_Park)",
  ),
  fact(
    "bethesda-terrace",
    ["the-lake", "central-park-landmarks"],
    "The park's formal heart",
    "Bethesda Terrace is the architectural centerpiece of Central Park's original plan.",
    "The terrace links the Mall to the Lake through stairs, arcades, and an open plaza. Its carved stone panels depict nature and the seasons, bringing detailed ornament into the larger landscape.",
    "Bethesda_Terrace_and_Fountain",
  ),
  fact(
    "bethesda-fountain",
    ["the-lake", "central-park-landmarks"],
    "Water celebrating water",
    "Bethesda Fountain commemorates the Croton Aqueduct, which brought reliable fresh water to New York.",
    "Emma Stebbins designed the Angel of the Waters sculpture, unveiled in 1873. The angel refers to a biblical healing pool while the fountain celebrates the city's transformative water system.",
    "Bethesda_Terrace_and_Fountain",
  ),
  fact(
    "central-park-zoo",
    ["central-park-landmarks"],
    "From menagerie to zoo",
    "Central Park's informal animal collection became an official menagerie in 1864.",
    "The collection was rebuilt as a city zoo in 1934 and extensively redesigned in the 1980s around naturalistic habitats. It is much smaller than the Bronx Zoo encountered later in the journey.",
    "Central_Park_Zoo",
  ),
  fact(
    "arsenal",
    ["central-park-landmarks"],
    "A building older than the park",
    "The Central Park Arsenal was completed in 1851, before the park around it existed.",
    "Built to store arms for New York State's militia, the fortress-like brick structure later housed park offices and the original menagerie. It remains near the zoo on Fifth Avenue.",
    "Arsenal_(Central_Park)",
  ),
  fact(
    "grand-army-plaza",
    ["central-park-landmarks"],
    "A formal gateway at 59th Street",
    "Grand Army Plaza forms the southeast entrance to Central Park.",
    "Fifth Avenue divides the plaza into two parts. The northern half contains the gilded equestrian statue of William Tecumseh Sherman; the southern half includes the Pulitzer Fountain.",
    "Grand_Army_Plaza_(Manhattan)",
  ),
  fact(
    "fifth-avenue-station",
    ["central-park-landmarks", "subway"],
    "A station beside the park",
    "The Fifth Avenue–59th Street station opened in 1919 on the BMT Broadway Line.",
    "Its location serves the southeast corner of Central Park and Grand Army Plaza. The N, R, and W services use the station today, while this game begins a longer fictionalized transfer journey from it.",
    "Fifth_Avenue–59th_Street_station",
  ),
  fact(
    "subway-opening",
    ["subway", "subway-train"],
    "The first underground run",
    "New York's first subway line opened on October 27, 1904.",
    "The original Interborough Rapid Transit route ran from City Hall north through Manhattan, then split toward the Upper West Side and the Bronx. Elevated railways had already served New Yorkers for decades.",
    "History_of_the_New_York_City_Subway",
  ),
  fact(
    "subway-stations",
    ["subway", "subway-train"],
    "Hundreds of places to stop",
    "The New York City Subway has 472 stations when each physical station is counted separately.",
    "Connected station complexes are sometimes counted as a single stop, producing a smaller total. Either way, the network has more stations than any other rapid-transit system by the common physical-station count.",
    "New_York_City_Subway_stations",
  ),
  fact(
    "subway-boroughs",
    ["subway", "subway-train"],
    "Four boroughs by rail",
    "The subway serves Manhattan, Brooklyn, Queens, and the Bronx—but not Staten Island.",
    "Staten Island has its own rapid-transit line, the Staten Island Railway. It uses subway-like cars but is not physically connected to the subway network.",
    "New_York_City_Subway",
  ),
  fact(
    "subway-above-ground",
    ["subway", "subway-train"],
    "Subway does not always mean underground",
    "About 40 percent of New York City Subway track is above ground.",
    "Outside central Manhattan, trains often run on elevated structures, embankments, or in open cuts. The system's name describes the whole network, not the position of every track.",
    "New_York_City_Subway",
  ),
  fact(
    "subway-line-service",
    ["subway", "subway-train"],
    "A line is not a service",
    "Subway routes such as 5, N, or R are services; the physical tracks they share are lines.",
    "A service can travel over several named lines, and several services can share one line. This is why a route bullet tells riders more than the track's infrastructure name.",
    "List_of_New_York_City_Subway_lines",
  ),
  fact(
    "subway-express",
    ["subway", "subway-train"],
    "Local outside, express inside",
    "Many four-track subway lines reserve the outer tracks for local trains and inner tracks for express trains.",
    "Local trains stop more often while express trains bypass selected stations. Track switches let services change patterns when construction or disruption requires it.",
    "New_York_City_Subway",
  ),
  fact(
    "subway-flat-fare",
    ["subway"],
    "One fare, many miles",
    "The subway uses a flat fare rather than charging by distance traveled.",
    "Once inside the paid area, a rider can transfer between connected subway services without paying again. New York chose this simple model even as the network grew far beyond the original routes.",
    "New_York_City_transit_fares",
  ),
  fact(
    "subway-metrocard",
    ["subway"],
    "The yellow card era",
    "The MetroCard entered public testing in 1993 and replaced subway tokens.",
    "Its magnetic stripe stored fare value or time-based passes. Contactless OMNY later succeeded it, so the game's MetroCard is also a small piece of transit history.",
    "MetroCard",
  ),
  fact(
    "subway-three-systems",
    ["subway", "subway-train"],
    "Three networks became one",
    "The IRT, BMT, and city-owned IND once operated as separate subway systems.",
    "New York City unified the three systems in 1940. Their engineering legacies remain: former IRT routes use narrower cars than former BMT and IND routes.",
    "History_of_the_New_York_City_Subway",
  ),
  fact(
    "subway-mosaics",
    ["subway"],
    "Wayfinding set in tile",
    "Early subway stations used colored tile, mosaics, and symbols to help riders identify stops.",
    "Many passengers in 1904 could not read English, so station ornament combined words with memorable shapes and color bands. Surviving mosaics still act as both signage and public art.",
    "New_York_City_Subway_tiles",
  ),
  fact(
    "subway-third-rail",
    ["subway-train"],
    "Power beside the rails",
    "Subway trains collect electricity from an exposed third rail beside the running rails.",
    "A contact shoe on the train slides along the electrified rail. The system avoids onboard fuel but makes track areas extremely dangerous and strictly off-limits.",
    "Third_rail",
  ),
  fact(
    "subway-zebra-board",
    ["subway-train"],
    "Why conductors point",
    "New York conductors point at a striped board when a train is correctly aligned in the station.",
    "The black-and-white conductor's board marks the position from which the crew can safely open the doors. Pointing confirms that the full train is alongside the platform.",
    "Pointing_and_calling",
  ),
  fact(
    "subway-route-shapes",
    ["subway-train"],
    "Circles and diamonds carry meaning",
    "On numbered services, a circle usually marks local service and a diamond marks an express variant.",
    "The same route number can use different stopping patterns in different places or times. Shape, number, destination, and platform signs all work together as wayfinding clues.",
    "New_York_City_Subway_nomenclature",
  ),
  fact(
    "subway-map",
    ["subway-train"],
    "A map that bends geography",
    "The subway map simplifies New York so routes and transfers are easier to follow.",
    "Modern versions descend from a 1979 design led by Michael Hertz Associates. Shorelines, streets, and route curves are adjusted because a useful transit diagram is not the same thing as a precise street map.",
    "New_York_City_Subway_map",
  ),
  fact(
    "bronx-zoo-opening",
    ["bronx-zoo"],
    "A zoo since 1899",
    "The Bronx Zoo opened on November 8, 1899, in Bronx Park.",
    "It was created by the New York Zoological Society, now the Wildlife Conservation Society. Its early mission combined public exhibition with the study and protection of wildlife.",
    "Bronx_Zoo",
  ),
  fact(
    "bronx-zoo-size",
    ["bronx-zoo"],
    "A river runs through it",
    "The Bronx Zoo occupies 265 acres divided by the Bronx River.",
    "Its unusually large urban site allows long walking routes and naturalistic habitats. The river is New York City's only freshwater river and continues south toward the East River.",
    "Bronx_Zoo",
  ),
  fact(
    "bronx-zoo-naturalism",
    ["bronx-zoo"],
    "Habitats instead of rows of cages",
    "The Bronx Zoo became known for grouping animals in naturalistic landscape settings.",
    "Moats, terrain, vegetation, and carefully planned sightlines can separate animals and visitors with fewer visible bars. Later exhibits also grouped species by ecosystem and conservation story.",
    "Bronx_Zoo",
  ),
  fact(
    "bronx-zoo-wcs",
    ["bronx-zoo"],
    "One zoo in a larger network",
    "The Wildlife Conservation Society operates the Bronx Zoo and four other New York wildlife parks.",
    "The same organization runs the Central Park, Queens, and Prospect Park zoos and the New York Aquarium. It also supports field conservation programs around the world.",
    "Wildlife_Conservation_Society",
  ),
  fact(
    "bronx-zoo-congo",
    ["bronx-zoo"],
    "A forest with a conservation vote",
    "Congo Gorilla Forest links a major zoo habitat with support for field conservation.",
    "The 6.5-acre exhibit presents a Central African rainforest ecosystem. A portion of its admission fee has been directed toward conservation work, and visitors can choose projects to support.",
    "Bronx_Zoo",
  ),
  fact(
    "bronx-zoo-madagascar",
    ["bronx-zoo"],
    "An old lion house became Madagascar",
    "The zoo's Madagascar! exhibit occupies the renovated former Lion House.",
    "The historic building was adapted to recreate several habitats from the island of Madagascar. Its species and displays emphasize both the island's extraordinary endemism and threats to its wildlife.",
    "Bronx_Zoo",
  ),
  fact(
    "polar-bear-marine",
    ["zoo-polar-bear"],
    "A bear classified as a marine mammal",
    "The polar bear's scientific name, Ursus maritimus, means “maritime bear.”",
    "Polar bears depend on Arctic sea ice to hunt seals, travel, mate, and sometimes den. In the United States they are protected under the Marine Mammal Protection Act as well as other wildlife laws.",
    "Polar_bear",
  ),
  fact(
    "polar-bear-coat",
    ["zoo-polar-bear"],
    "White-looking fur, dark skin",
    "Polar bear hairs are not white with pigment; their coat scatters light above dark skin.",
    "Dense underfur and longer guard hairs insulate the body. The pale-looking coat provides camouflage against snow and ice, while the skin beneath it is black.",
    "Polar_bear",
  ),
  fact(
    "polar-bear-paws",
    ["zoo-polar-bear"],
    "Paws built for ice and water",
    "A polar bear's broad paws spread its weight on snow and work like paddles while swimming.",
    "The front paws propel the bear through water while the hind feet steer. Rough footpads and small bumps called papillae help create traction on slippery ice.",
    "Polar_bear",
  ),
  fact(
    "polar-bear-size",
    ["zoo-polar-bear"],
    "One of the largest living bears",
    "Adult male polar bears can weigh several times as much as adult females.",
    "This strong sexual size difference is called sexual dimorphism. Polar bears and Kodiak brown bears are the largest living members of the bear family.",
    "Polar_bear",
  ),
  fact(
    "sloth-species",
    ["zoo-sloth"],
    "Two toes, three toes, six species",
    "Six living sloth species belong to two-toed and three-toed sloth families.",
    "The familiar names count the long claws on the front limbs: all living sloths have three toes on each hind foot. Two-toed and three-toed sloths also differ in anatomy, diet, and daily activity.",
    "Sloth",
  ),
  fact(
    "sloth-metabolism",
    ["zoo-sloth"],
    "Slow is an energy strategy",
    "Sloths have exceptionally low metabolic rates for mammals of their size.",
    "A leafy diet supplies relatively little usable energy and can take a long time to digest. Slow movement, long rest periods, and variable body temperature all help sloths conserve energy.",
    "Sloth",
  ),
  fact(
    "sloth-fur-ecosystem",
    ["zoo-sloth"],
    "A tiny ecosystem in the fur",
    "Sloth fur can host algae, moths, beetles, and other organisms.",
    "Grooves and cracks in the outer hairs can hold moisture where algae grows. The greenish tint may help camouflage a sloth in the canopy, while the full fur community forms a miniature ecosystem.",
    "Sloth",
  ),
  fact(
    "sloth-upside-down",
    ["zoo-sloth"],
    "Anatomy for hanging around",
    "Long curved claws let sloths suspend themselves beneath branches with little muscular effort.",
    "Their limbs, tendons, and grip are specialized for life below the canopy rather than running on the ground. Even the direction of their fur helps rain drain away while the animal hangs upside down.",
    "Sloth",
  ),
  fact(
    "sea-lion-ears",
    ["zoo-sea-lion"],
    "Look for ear flaps",
    "California sea lions have visible external ear flaps; true seals do not.",
    "Sea lions are eared seals in the family Otariidae. Their long front flippers and rotating hind limbs also let them move on land differently from earless seals.",
    "California_sea_lion",
  ),
  fact(
    "sea-lion-swim",
    ["zoo-sea-lion"],
    "Front-flipper swimmers",
    "California sea lions generate most of their swimming power with their large front flippers.",
    "Their streamlined bodies and winglike forelimbs make them agile underwater. Hind flippers help with steering and can rotate forward beneath the body for walking on land.",
    "California_sea_lion",
  ),
  fact(
    "sea-lion-range",
    ["zoo-sea-lion"],
    "A Pacific coast neighbor",
    "California sea lions live along the western coast of North America.",
    "They breed from central Mexico north into California and are famous for gathering on docks and rocky shores. Their diet includes fish and squid.",
    "California_sea_lion",
  ),
  fact(
    "sea-lion-dimorphism",
    ["zoo-sea-lion"],
    "Males can be much larger",
    "Adult male California sea lions grow far heavier than adult females.",
    "Mature males also develop a pronounced forehead crest. This difference between sexes is called sexual dimorphism and reflects the species' competitive breeding system.",
    "California_sea_lion",
  ),
  fact(
    "spider-tail",
    ["zoo-spider-monkey"],
    "A fifth limb",
    "A spider monkey's prehensile tail can grip branches and support its body.",
    "The underside near the tail tip has a hairless gripping pad with ridged skin. This gives the monkey another secure contact while reaching or traveling through the canopy.",
    "Spider_monkey",
  ),
  fact(
    "spider-hands",
    ["zoo-spider-monkey"],
    "Hooklike hands",
    "Spider monkeys have long fingers and greatly reduced thumbs.",
    "Their hands work like hooks during arm-swinging movement, while the prehensile tail provides extra support. Long limbs give the group its spider-like name.",
    "Spider_monkey",
  ),
  fact(
    "spider-canopy",
    ["zoo-spider-monkey"],
    "Built for the upper forest",
    "Spider monkeys spend most of their time high in tropical forest canopies.",
    "They move by climbing, leaping, arm swinging, and suspended travel. Fruit makes up much of their diet, so healthy forests with many fruiting trees are essential.",
    "Spider_monkey",
  ),
  fact(
    "spider-society",
    ["zoo-spider-monkey"],
    "A group that changes size",
    "Spider monkey communities often split into smaller parties and reunite later.",
    "This flexible pattern is called fission–fusion social organization. It lets individuals spread out when food is scattered and gather when conditions allow.",
    "Fission–fusion_society",
  ),
  fact(
    "sun-conure-range",
    ["zoo-birds"],
    "A parrot from a small range",
    "The sun conure is native to a limited area of northeastern South America.",
    "Wild populations occur mainly around Guyana and northern Brazil. Habitat loss and trapping for the bird trade contributed to a severe decline.",
    "Sun_conure",
  ),
  fact(
    "sun-conure-color",
    ["zoo-birds"],
    "Color arrives with age",
    "Young sun conures have more green plumage than bright orange adults.",
    "The greener juvenile colors gradually give way to yellow, orange, red, blue, and green adult plumage. The change unfolds over molts rather than happening at once.",
    "Sun_conure",
  ),
  fact(
    "bird-feathers",
    ["zoo-birds"],
    "Feathers do several jobs",
    "Feathers support flight, insulation, waterproofing, display, and camouflage.",
    "Different feather types are specialized for different tasks. Birds maintain them by preening, which aligns tiny structures and spreads protective oils in many species.",
    "Feather",
  ),
  fact(
    "bird-air-sacs",
    ["zoo-birds"],
    "Air moves one way through bird lungs",
    "Bird air sacs help keep fresh air moving through the lungs during both inhaling and exhaling.",
    "The sacs themselves do not perform most gas exchange; they act like bellows. This efficient flow supports the high energy demands of flight.",
    "Bird_anatomy",
  ),
  fact(
    "zebra-species",
    ["zoo-zebra"],
    "Three living zebra species",
    "Plains, mountain, and Grévy's zebras are distinct species.",
    "All are African members of the horse family, Equidae. They differ in body size, stripe pattern, range, habitat, and social organization.",
    "Zebra",
  ),
  fact(
    "zebra-stripes-unique",
    ["zoo-zebra"],
    "No two stripe maps are identical",
    "Individual zebras can be recognized by their distinctive stripe patterns.",
    "Researchers use photographs of stripe arrangements as a noninvasive way to identify and follow animals. Pattern details vary among species and across the body.",
    "Zebra",
  ),
  fact(
    "zebra-flies",
    ["zoo-zebra"],
    "Stripes may confuse biting flies",
    "Evidence suggests zebra stripes reduce successful landings by biting flies.",
    "Scientists have proposed many functions for stripes, including social signaling and temperature effects. Experiments strongly support a role in discouraging tabanid flies, though stripe evolution remains an active research topic.",
    "Zebra",
  ),
  fact(
    "zebra-senses",
    ["zoo-zebra"],
    "Eyes and ears scan widely",
    "Zebras have side-facing eyes and mobile ears that help monitor their surroundings.",
    "Wide visual coverage and independently turning ears are useful on open grasslands. Herd members also alert one another to danger.",
    "Zebra",
  ),
  fact(
    "red-panda-family",
    ["zoo-red-panda"],
    "Not a little giant panda",
    "The red panda is the only living member of the family Ailuridae.",
    "Despite the shared name and bamboo diet, red pandas are not close relatives of giant pandas. Modern classification places them in their own family within the musteloid group.",
    "Red_panda",
  ),
  fact(
    "red-panda-range",
    ["zoo-red-panda"],
    "Mountain forest specialist",
    "Red pandas live in temperate forests of the eastern Himalayas and southwestern China.",
    "They depend on cool, forested habitat with dense bamboo beneath the canopy. Habitat fragmentation is one of their major conservation threats.",
    "Red_panda",
  ),
  fact(
    "red-panda-thumb",
    ["zoo-red-panda"],
    "A wrist bone that grips",
    "Red pandas use an enlarged wrist bone like a false thumb to hold bamboo.",
    "The structure is a modified radial sesamoid rather than a true sixth finger. Giant pandas independently evolved a similar bamboo-gripping adaptation.",
    "Red_panda",
  ),
  fact(
    "red-panda-tail",
    ["zoo-red-panda"],
    "A blanket with balance",
    "A red panda's long ringed tail helps with balance and can wrap around the body for warmth.",
    "Red pandas are capable climbers and often rest in trees. Their thick fur even covers the soles of their feet, adding insulation in cold mountain climates.",
    "Red_panda",
  ),
  fact(
    "tortoise-islands",
    ["zoo-tortoise"],
    "Giants from Aldabra",
    "Aldabra giant tortoises come from the Aldabra Atoll in the Seychelles.",
    "The remote coral atoll supports the world's largest wild population of giant tortoises. Their grazing and trail-making strongly shape the island ecosystem.",
    "Aldabra_giant_tortoise",
  ),
  fact(
    "tortoise-size",
    ["zoo-tortoise"],
    "Among the largest tortoises",
    "Adult male Aldabra giant tortoises can weigh hundreds of pounds.",
    "Their massive, domed bodies store energy and water for life in a seasonally dry environment. Males generally grow larger than females.",
    "Aldabra_giant_tortoise",
  ),
  fact(
    "tortoise-shell",
    ["zoo-tortoise"],
    "A shell is living skeleton",
    "A tortoise shell is made of bone fused with the ribs and vertebrae.",
    "The bony shell is covered by keratin plates called scutes in most tortoises. Because it is integrated with the skeleton, a tortoise cannot leave its shell.",
    "Turtle_shell",
  ),
  fact(
    "tortoise-longevity",
    ["zoo-tortoise"],
    "Lives measured in human generations",
    "Giant tortoises are among the longest-lived vertebrates.",
    "Some documented individuals have lived well beyond a century. Slow growth, low adult predation, and slow metabolism all accompany their remarkable lifespans.",
    "Aldabra_giant_tortoise",
  ),
  fact(
    "flamingo-color",
    ["zoo-flamingo"],
    "Pink comes from food",
    "Flamingos obtain red and orange carotenoid pigments from their diet.",
    "The pigments are metabolized and deposited in feathers and skin. Without enough dietary carotenoids, flamingo plumage becomes much paler.",
    "Flamingo",
  ),
  fact(
    "flamingo-filter",
    ["zoo-flamingo"],
    "An upside-down filter",
    "Flamingos use specialized bills to filter small organisms and particles from water.",
    "Rows of comb-like lamellae line the bill, and a muscular tongue pumps water through them. The bent bill works most effectively when the head is held upside down.",
    "Flamingo",
  ),
  fact(
    "flamingo-leg",
    ["zoo-flamingo"],
    "The backward bend is an ankle",
    "The joint halfway down a flamingo's visible leg is its ankle, not its knee.",
    "The true knee sits higher, close to the body and often hidden by feathers. What looks like a long lower leg is largely an elongated foot bone.",
    "Bird_anatomy",
  ),
  fact(
    "flamingo-one-leg",
    ["zoo-flamingo"],
    "Standing with little effort",
    "Flamingos can rest on one leg with remarkably little muscular work.",
    "Their joints can passively support the body in a stable posture. One-leg standing may also reduce heat loss when birds are in cool water.",
    "Flamingo",
  ),
  fact(
    "bison-largest",
    ["zoo-bison"],
    "North America's heavyweight",
    "The American bison is the largest living land animal in North America.",
    "Large bulls can exceed a metric ton. Their massive shoulder hump is supported by long vertebral spines and powerful muscles used to move the head and plow through snow.",
    "American_bison",
  ),
  fact(
    "bison-not-buffalo",
    ["zoo-bison"],
    "Bison, not true buffalo",
    "American bison are commonly called buffalo, but true buffalo are native to Africa and Asia.",
    "Bison and buffalo are related bovids, yet they belong to different genera. The familiar North American name remains culturally and historically important.",
    "American_bison",
  ),
  fact(
    "bison-keystone",
    ["zoo-bison"],
    "Grassland engineers",
    "Bison grazing, wallowing, and movement create varied habitat across prairies.",
    "Their wallows hold water, their grazing changes plant structure, and their fur can transport seeds. Many other grassland organisms respond to the patchwork they produce.",
    "American_bison",
  ),
  fact(
    "bison-bronx-conservation",
    ["zoo-bison", "bronx-zoo"],
    "Bison traveled from the Bronx to the West",
    "In 1913, fourteen Bronx Zoo bison were sent to new protected herds in the American West.",
    "The transfer, organized with the American Bison Society, helped establish herds at the National Bison Range and Wind Cave National Park after the species had nearly vanished.",
    "American_Bison_Society",
  ),
  fact(
    "city-five-boroughs",
    ["city"],
    "Five boroughs, one city",
    "Modern New York City was consolidated from five boroughs in 1898.",
    "Manhattan, Brooklyn, Queens, the Bronx, and Staten Island are each both a borough and part of a county. The consolidation joined communities separated by rivers, harbors, and distinct local histories.",
    "Boroughs_of_New_York_City",
  ),
  fact(
    "city-bronx-mainland",
    ["city"],
    "The mainland borough",
    "The Bronx is the only New York City borough mostly located on the North American mainland.",
    "Manhattan and Staten Island are islands, while Brooklyn and Queens occupy the western end of Long Island. Marble Hill is politically Manhattan but geographically attached to the mainland.",
    "Geography_of_New_York_City",
  ),
  fact(
    "city-grid",
    ["city"],
    "The 1811 street grid",
    "The Commissioners' Plan of 1811 laid out Manhattan's numbered streets and avenues.",
    "Its regular grid made land easier to divide and develop as the city expanded north. The plan largely ignored Manhattan's existing hills, streams, farms, and older roads.",
    "Commissioners' Plan_of_1811",
  ),
  fact(
    "city-broadway",
    ["city"],
    "Broadway breaks the pattern",
    "Broadway follows an older route and cuts diagonally across much of Manhattan's grid.",
    "Its angled intersections created famous spaces including Times Square, Herald Square, and Madison Square. Parts of the route trace streets that existed before the 1811 plan.",
    "Broadway_(Manhattan)",
  ),
  fact(
    "city-manhattanhenge",
    ["city"],
    "Sunset down the cross streets",
    "Twice each year, sunset lines up closely with Manhattan's east-west street grid.",
    "The event is nicknamed Manhattanhenge. Because the grid is rotated from true east-west, the alignment happens around late May and mid-July rather than on the equinoxes.",
    "Manhattanhenge",
  ),
  fact(
    "city-cabs",
    ["city"],
    "Why taxis are yellow",
    "New York's medallion taxicabs are painted yellow so licensed street-hail cars are easy to recognize.",
    "The city standardized yellow for medallion cabs in the late 1960s. Green boro taxis later gained permission to accept street hails outside Manhattan's central business district and at selected northern Manhattan locations.",
    "Taxis_of_New_York_City",
  ),
  fact(
    "city-bronx-river-parkway",
    ["city"],
    "A road designed with a river park",
    "The Bronx River Parkway was among the earliest limited-access automobile parkways in the United States.",
    "Built alongside a restored river corridor, it paired transportation with landscape conservation. Its success influenced later parkway construction around New York.",
    "Bronx_River_Parkway",
  ),
  fact(
    "city-cross-bronx",
    ["city"],
    "An expressway across the Bronx",
    "The Cross Bronx Expressway carries Interstate 95 through the heart of the borough.",
    "Construction began in the late 1940s and required major rock cuts, viaducts, and the displacement of thousands of residents. Its route and neighborhood effects remain central to debates about urban highway planning.",
    "Cross_Bronx_Expressway",
  ),
  fact(
    "city-henry-hudson-parkway",
    ["city"],
    "A parkway beside the Hudson",
    "The Henry Hudson Parkway follows Manhattan's west side beside the river and Riverside Park.",
    "It continues the West Side Highway northward as New York State Route 9A. The landscaped road was built in stages and named for explorer Henry Hudson.",
    "Henry_Hudson_Parkway",
  ),
  fact(
    "city-hudson-estuary",
    ["city"],
    "A river that feels the ocean",
    "The lower Hudson is a tidal estuary, so salt water and tides reach far upriver from New York Harbor.",
    "Its water level rises and falls with the Atlantic tides. Fresh river water mixes with salt water in a changing estuarine system used by migratory fish, birds, and many other organisms.",
    "Hudson_River",
  ),
  fact(
    "city-upper-west-side",
    ["city", "museum"],
    "Between park and river",
    "The Upper West Side occupies the band of Manhattan between Central Park and the Hudson River.",
    "The neighborhood is commonly described as stretching from West 59th Street to West 110th Street. The museum stands on its eastern edge, facing Central Park across Central Park West.",
    "Upper_West_Side",
  ),
  fact(
    "city-west-79th",
    ["city"],
    "A crosstown route at 79th Street",
    "West 79th Street links the Hudson-side highway with Central Park West and the museum district.",
    "A sunken transverse road continues the street's crosstown function through Central Park. Separating that traffic below park paths was one of the landscape's important circulation ideas.",
    "79th_Street_(Manhattan)",
  ),
  fact(
    "city-central-park-west",
    ["city", "museum"],
    "Eighth Avenue changes its name",
    "The avenue along Central Park's west edge is called Central Park West.",
    "South of Columbus Circle and north of Frederick Douglass Circle, the same general avenue alignment uses different names. The museum's grand facade faces this park-side boulevard.",
    "Central_Park_West",
  ),
  fact(
    "city-skyscrapers",
    ["city"],
    "A skyline shaped by zoning",
    "New York's 1916 Zoning Resolution encouraged skyscraper setbacks.",
    "The rule aimed to preserve light and air at street level by limiting how high a building could rise before stepping back. Its requirements helped create the city's classic wedding-cake tower profiles.",
    "1916_Zoning_Resolution",
  ),
  fact(
    "city-water-tanks",
    ["city"],
    "Wooden tanks above the roofs",
    "Many New York buildings store water in rooftop tanks because city pressure cannot reliably reach high floors.",
    "Pumps fill the tank, then gravity supplies the building below. Traditional wooden tanks are relatively light, inexpensive, and resistant to freezing when water is regularly used.",
    "Water_tower",
  ),
  fact(
    "museum-founding",
    ["museum"],
    "A museum born in the park",
    "The American Museum of Natural History was founded in 1869.",
    "Its first displays opened in Central Park's Arsenal in 1871. The first purpose-built section of the present complex opened across the park in 1877.",
    "American_Museum_of_Natural_History",
  ),
  fact(
    "museum-collections",
    ["museum"],
    "Most treasures are behind the scenes",
    "AMNH collections contain about 32 million specimens and cultural objects.",
    "Only a small fraction can be displayed at once. The rest support research in fields including zoology, paleontology, anthropology, earth science, genomics, and astrophysics.",
    "American_Museum_of_Natural_History",
  ),
  fact(
    "museum-blue-whale",
    ["museum"],
    "A blue whale overhead",
    "The Milstein Hall of Ocean Life suspends a 94-foot model of a blue whale.",
    "The full-size model is based on a female found in 1925. Blue whales are the largest animals known to have lived, even exceeding the mass of the largest dinosaurs.",
    "Milstein_Hall_of_Ocean_Life",
  ),
  fact(
    "museum-ahnighto",
    ["museum"],
    "A meteorite needs deep support",
    "The 34-ton Ahnighito meteorite is so heavy that its supports descend to Manhattan bedrock.",
    "Ahnighito is the largest fragment of the Cape York meteorite on display at the museum. It is mostly iron and nickel and fell to Earth thousands of years ago.",
    "Cape_York_meteorite",
  ),
  fact(
    "museum-star-india",
    ["museum"],
    "A star inside a sapphire",
    "The Star of India is a 563-carat star sapphire displayed at AMNH.",
    "Tiny aligned inclusions inside the stone reflect light as a six-rayed star, an optical effect called asterism. The gem was among the objects stolen from the museum in 1964 and later recovered.",
    "Star_of_India_(gem)",
  ),
  fact(
    "museum-trex",
    ["museum"],
    "A famous composite predator",
    "AMNH's standing Tyrannosaurus rex mount combines real fossil material from two individuals.",
    "The dramatic skeleton is assembled to represent one animal, but missing bones can be supplied by casts or material from another specimen. Composite mounts help museums present a complete body while preserving scientific evidence.",
    "AMNH_5027",
  ),
  fact(
    "museum-titanosaur",
    ["museum"],
    "A dinosaur longer than its room",
    "The museum's titanosaur cast is about 122 feet long and extends beyond its gallery doorway.",
    "The mount represents Patagotitan mayorum, one of the largest dinosaurs known from substantial remains. Its long neck and tail turn a single skeleton into a lesson in scale.",
    "Patagotitan",
  ),
  fact(
    "museum-barosaurus",
    ["museum"],
    "A sauropod rises in the rotunda",
    "The museum's Barosaurus scene shows an adult rearing to defend a juvenile from Allosaurus.",
    "The freestanding group in the Theodore Roosevelt Rotunda turns biomechanical interpretation into a huge three-dimensional moment. Its pose is reconstructed from fossil anatomy, not observed behavior.",
    "Barosaurus",
  ),
  fact(
    "museum-dioramas",
    ["museum"],
    "Dioramas are scientific compositions",
    "AMNH habitat dioramas combine specimens, painted backgrounds, sculpture, and reconstructed plants.",
    "Artists and scientists used field sketches, photographs, measurements, and collected material to build convincing places. Forced perspective makes the shallow cases appear much deeper.",
    "Diorama",
  ),
  fact(
    "museum-akeley",
    ["museum"],
    "The habitat diorama transformed",
    "Carl Akeley helped pioneer the naturalistic museum habitat groups seen in the African mammal halls.",
    "Akeley developed new taxidermy and display techniques to place carefully modeled animals within detailed ecosystems. His work strongly influenced how museums present animal behavior and habitat.",
    "Carl_Akeley",
  ),
  fact(
    "museum-cladogram",
    ["museum"],
    "Follow the branches of life",
    "The fossil halls organize many displays around cladograms—diagrams of evolutionary relationships.",
    "A cladogram groups organisms by shared derived traits rather than simply lining them up from 'primitive' to 'advanced.' Each branch point represents a hypothesis about common ancestry.",
    "Cladistics",
  ),
  fact(
    "museum-rose-center",
    ["museum"],
    "A sphere for space",
    "The Rose Center's Hayden Sphere contains the Space Theater and Big Bang Theater.",
    "Completed in 2000, the great sphere appears to float inside a glass cube. The surrounding cosmic pathway uses changes in scale to tell the history of the universe.",
    "Rose_Center_for_Earth_and_Space",
  ),
  fact(
    "museum-megatherium-size",
    ["museum"],
    "A sloth the size of an elephant",
    "Megatherium was one of the largest ground sloths, reaching the mass of an elephant.",
    "It lived in South America from the Pliocene into the Pleistocene. Its huge skeleton combines a massive pelvis, powerful limbs, and long claws unlike those of today's tree sloths.",
    "Megatherium",
  ),
  fact(
    "museum-megatherium-stance",
    ["museum"],
    "Built to rear up",
    "Megatherium could support itself on its hind limbs and strong tail while reaching upward.",
    "This tripod-like stance may have helped it pull vegetation within reach. Large claws were useful tools, while the broad tail provided an additional brace.",
    "Megatherium",
  ),
  fact(
    "museum-megatherium-history",
    ["museum"],
    "A fossil that shaped paleontology",
    "A Megatherium skeleton described in 1796 was one of the first extinct mammals reconstructed scientifically.",
    "Georges Cuvier used its anatomy to argue that extinction was real, a disputed idea at the time. Ground sloths therefore played an important role in the birth of vertebrate paleontology.",
    "Megatherium",
  ),
  fact(
    "museum-lucy",
    ["museum"],
    "A cast of a famous ancestor",
    "The Hall of Human Origins includes a cast of Lucy, a 3.2-million-year-old Australopithecus afarensis skeleton.",
    "The original fossils were discovered in Ethiopia in 1974. About 40 percent of the skeleton was recovered, providing important evidence about early upright walking.",
    "Lucy_(Australopithecus)",
  ),
  fact(
    "museum-northwest-coast",
    ["museum"],
    "The museum's oldest hall",
    "The Northwest Coast Hall was established in 1899 and has been reinterpreted with Indigenous collaborators.",
    "Its collections include monumental carvings, house posts, textiles, tools, and a Haida canoe. The renovated hall presents living cultures and contemporary voices rather than treating them only as history.",
    "American_Museum_of_Natural_History",
  ),
];

export const EDUCATION_CONTEXT_LABELS: Record<EducationContext, string> = {
  "central-park": "Central Park field notes",
  "central-park-landmarks": "Park landmarks",
  "the-lake": "The Lake and its wildlife",
  subway: "New York City Subway",
  "subway-train": "On board the subway",
  "bronx-zoo": "Bronx Zoo",
  "zoo-polar-bear": "Polar bears",
  "zoo-sloth": "Sloths",
  "zoo-sea-lion": "California sea lions",
  "zoo-spider-monkey": "Spider monkeys",
  "zoo-birds": "Birds and the aviary",
  "zoo-zebra": "Zebras",
  "zoo-red-panda": "Red pandas",
  "zoo-tortoise": "Giant tortoises",
  "zoo-flamingo": "Flamingos",
  "zoo-bison": "American bison",
  city: "New York City",
  museum: "American Museum of Natural History",
  homecoming: "Central Park homecoming",
};

export function factsForContext(context: EducationContext) {
  if (context === "bronx-zoo") {
    return EDUCATION_FACTS.filter(entry =>
      entry.contexts.includes(context) ||
      entry.contexts.some(entryContext => entryContext.startsWith("zoo-")),
    );
  }
  return EDUCATION_FACTS.filter(entry => entry.contexts.includes(context));
}

export function wikipediaUrlForFact(entry: EducationFact) {
  return `https://en.wikipedia.org/wiki/${encodeURIComponent(entry.wikiTitle).replace(/%2F/g, "/")}`;
}

export function educationContextForParkStage(stage: string): EducationContext {
  if (stage === "BOW_BRIDGE") return "central-park-landmarks";
  if (stage === "LAKE_TICKET") return "the-lake";
  if (stage === "SUBWAY_ENTRANCE") return "subway";
  return "central-park";
}

export function educationContextForTransitStage(stage: string, objective: string): EducationContext {
  if (stage === "RIDING") return "subway-train";
  if (stage === "BUS_DRIVE") return "city";
  if (stage === "MUSEUM" || stage === "COMPLETE") return "museum";
  if (stage === "CENTRAL_PARK") return "homecoming";
  if (stage !== "BRONX_ZOO") return "subway";

  const cue = objective.toUpperCase();
  if (cue.includes("POLAR") || cue.includes("GARY")) return "zoo-polar-bear";
  if (cue.includes("SEA LION") || cue.includes("CURRENT")) return "zoo-sea-lion";
  if (cue.includes("MONKEY") || cue.includes("CANOPY")) return "zoo-spider-monkey";
  if (cue.includes("AVIARY") || cue.includes("BIRD")) return "zoo-birds";
  if (cue.includes("ZEBRA") || cue.includes("STRIPE")) return "zoo-zebra";
  if (cue.includes("PANDA") || cue.includes("SCENT")) return "zoo-red-panda";
  if (cue.includes("TORTOISE") || cue.includes("SUN TRAIL")) return "zoo-tortoise";
  if (cue.includes("FLAMINGO") || cue.includes("WETLAND")) return "zoo-flamingo";
  if (cue.includes("BISON") || cue.includes("PRAIRIE")) return "zoo-bison";
  if (cue.includes("SLOTH")) return "zoo-sloth";
  return "bronx-zoo";
}
